import React from "react";
import {Easing, interpolate, spring, useCurrentFrame, useVideoConfig} from "remotion";
import type {JasonWuCue} from "./timeline";
import type {LayoutEffectProps} from "./DemoEffectComponents";
import {getStaggerStartFrame, resolveContentItems, resolveContentText} from "./layoutRuntime";

const C = {blue: "var(--primary-accent)", gold: "#FFD166", green: "#36D399", red: "#FF5B6E", white: "#FFFFFF", dim: "rgba(255,255,255,.58)", panel: "var(--card-panel)"};
const ease = Easing.bezier(.16, 1, .3, 1);
const startFrame = (cue: JasonWuCue, fps: number) => Math.round(cue.start * fps) + 8;
const enter = (frame: number, start: number, x = -28) => ({opacity: interpolate(frame, [start, start + 24], [0, 1], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease}), transform: `translateX(${interpolate(frame, [start, start + 24], [x, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease})}px)`});
const Panel: React.FC<{children: React.ReactNode; color?: string; style?: React.CSSProperties}> = ({children, color = C.blue, style}) => <div style={{background: C.panel, border: `1px solid ${color}`, borderRadius: 10, boxShadow: `0 0 28px color-mix(in srgb, ${color} 25%, transparent)`, ...style}}>{children}</div>;
const Mark: React.FC<{value: string; color: string}> = ({value, color}) => <div style={{width: 46, height: 46, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", color, fontSize: 33, fontWeight: 950, border: `2px solid ${color}`, boxShadow: `0 0 18px color-mix(in srgb, ${color} 70%, transparent)`}}>{value}</div>;
const textProp = (props: Record<string, unknown> | undefined, key: string, fallback: string) => typeof props?.[key] === "string" && props[key].trim() ? props[key].trim() : fallback;
const listProp = (cue: JasonWuCue, props: Record<string, unknown> | undefined, key: string) => resolveContentItems(cue, props, [key, "items", "steps", "units", "comments", "nodes", "years"]);
const rows = (cue: JasonWuCue, props?: Record<string, unknown>) => resolveContentItems(cue, props, ["items", "steps", "units", "comments"]);
const boxColors: Record<string, string> = {purple: "#8B5CF6", blue: "#0A84FF", gold: "#FFD166", white: "#F8FAFC", green: "#36D399", red: "#FF6B6B"};
const boxColorProp = (props: Record<string, unknown> | undefined, fallback = C.blue) => boxColors[textProp(props, "boxColor", "auto")] ?? fallback;

export const RejectList: React.FC<LayoutEffectProps> = ({cue}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); return <div style={{position: "absolute", left: 98, top: 220, width: 690, ...enter(f, s)}}><div style={{color: C.red, fontSize: 22, fontWeight: 950, letterSpacing: 3}}>REJECTED PATHS</div><div style={{marginTop: 22, display: "flex", flexDirection: "column", gap: 14}}>{rows(cue).map((row, i) => <Panel key={row} color={C.red} style={{padding: "18px 22px", display: "flex", alignItems: "center", gap: 18, ...enter(f, s + 16 + i * 18)}}><Mark value="×" color={C.red}/><div><div style={{color: C.white, fontSize: 30, fontWeight: 950}}>{row}</div><div style={{marginTop: 4, color: "#FF9DA8", fontSize: 14, fontWeight: 900, letterSpacing: 2}}>CUT FROM THE PRODUCT PATH</div></div></Panel>)}</div></div>; };

export const CheckProgress: React.FC<LayoutEffectProps> = ({cue}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); const p = interpolate(f, [s + 20, s + 132], [0, 82], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease}); return <div style={{position: "absolute", left: 96, top: 245, width: 710, ...enter(f, s)}}><div style={{display: "flex", alignItems: "baseline", justifyContent: "space-between"}}><div style={{color: C.white, fontSize: 43, fontWeight: 950}}>PRODUCT RECOVERY</div><div style={{color: C.green, fontSize: 44, fontWeight: 950}}>{Math.round(p)}%</div></div><div style={{height: 22, marginTop: 18, background: "rgba(255,255,255,.12)", overflow: "hidden", borderRadius: 99}}><div style={{width: `${p}%`, height: "100%", background: C.green, boxShadow: "0 0 20px rgba(54,211,153,.9)"}}/></div><div style={{marginTop: 28, display: "flex", flexDirection: "column", gap: 13}}>{rows(cue).map((row, i) => <div key={row} style={{display: "flex", alignItems: "center", gap: 16, color: C.white, fontSize: 28, fontWeight: 900, ...enter(f, s + 36 + i * 18)}}><Mark value="✓" color={C.green}/>{row}</div>)}</div></div>; };

export const DiagonalChips: React.FC<LayoutEffectProps> = ({cue, props}) => {
  const f = useCurrentFrame();
  const {fps} = useVideoConfig();
  const s = startFrame(cue, fps);
  const designTokens = props?.designTokens && typeof props.designTokens === "object" ? props.designTokens as Record<string, unknown> : {};
  const gap = Math.max(0, Math.min(80, Number(designTokens.gap) || 8));
  const defaultItemCount = Math.max(1, Math.min(8, Math.round(Number(designTokens.defaultItemCount) || 4)));
  const staggerFrames = Math.max(0, Math.min(45, Math.round(Number(designTokens.staggerFrames) || Math.round(fps * 0.5))));
  const chips = listProp(cue, props, "items").slice(0, defaultItemCount);
  return <div style={{position: "absolute", left: 120, top: 224, width: 720, display: "flex", flexDirection: "column", gap}}>{chips.map((chip, i) => {
    const start = s + Math.round(fps * 0.5) + i * staggerFrames;
    const progress = interpolate(f, [start, start + 32], [0, 1], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease});
    const x = interpolate(progress, [0, 1], [-280, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp"});
    const y = interpolate(progress, [0, 1], [38, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp"});
    const color = [C.blue, C.gold, C.green][i % 3];
    return <div key={chip+"-"+i} style={{paddingLeft: i * 34, opacity: progress, transform: "translate3d("+x+"px,"+y+"px,0)", willChange: "transform, opacity"}}><Panel color={color} style={{width: 560, height: 104, boxSizing: "border-box", padding: "16px 24px", clipPath: "polygon(5% 0,100% 0,95% 100%,0 100%)"}}><div style={{color, fontSize: 14, fontWeight: 950, letterSpacing: 4}}>CHIP / {("0" + String(i + 1)).slice(-2)}</div><div style={{marginTop: 7, color: C.white, fontSize: 30, fontWeight: 950}}>{chip}</div></Panel></div>;
  })}</div>;
};

export const FloatingChips: React.FC<LayoutEffectProps> = ({cue, props}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); const chips = listProp(cue, props, "items").slice(0, 4); const pos = [[145,250],[530,190],[275,525],[750,485]]; return <div style={{position: "absolute", inset: 0}}>{chips.map((chip, i) => { const color = [C.blue, C.gold, C.green, C.blue][i]; return <Panel key={chip} color={color} style={{position: "absolute", left: pos[i]?.[0] ?? 145, top: (pos[i]?.[1] ?? 250) + Math.sin((f - s) / 17 + i) * 12, padding: "18px 22px", ...enter(f, s + getStaggerStartFrame(fps, i), i % 2 ? 34 : -34)}}><div style={{color: C.white, fontSize: 29, fontWeight: 950}}>{chip}</div></Panel>; })}</div>; };

export const BareTypography: React.FC<LayoutEffectProps> = ({cue}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); return <div style={{position: "absolute", left: 110, right: 130, top: 275, ...enter(f, s, -42)}}><div style={{width: interpolate(f, [s + 18, s + 70], [0, 164], {extrapolateLeft: "clamp", extrapolateRight: "clamp"}), height: 6, background: C.gold}}/><div style={{marginTop: 28, color: C.white, fontSize: 82, lineHeight: "96px", fontWeight: 950, maxWidth: 1160}}>{cue.section.subtitle}</div><div style={{marginTop: 26, color: C.blue, fontSize: 25, fontWeight: 950, letterSpacing: 5}}>{cue.section.eyebrow}</div><div style={{marginTop: 20, color: C.dim, fontSize: 32, lineHeight: "46px", maxWidth: 900}}>{cue.caption.zh}</div></div>; };

export const ChapterCard: React.FC<LayoutEffectProps> = ({cue}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); return <Panel color={C.blue} style={{position: "absolute", left: 112, top: 220, width: 760, padding: "34px 40px", ...enter(f, s)}}><div style={{color: C.blue, fontSize: 18, fontWeight: 950, letterSpacing: 5}}>CHAPTER / {cue.section.eyebrow}</div><div style={{marginTop: 20, color: C.white, fontSize: 60, lineHeight: "72px", fontWeight: 950}}>{cue.section.subtitle}</div><div style={{marginTop: 18, color: C.dim, fontSize: 27, fontWeight: 800}}>{cue.caption.zh}</div></Panel>; };

export const LogoWordmark: React.FC<LayoutEffectProps> = ({cue}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); const p = spring({frame: f - s, fps, config: {damping: 13, stiffness: 150}}); return <div style={{position: "absolute", left: 125, top: 270, display: "flex", alignItems: "center", gap: 32, ...enter(f, s), transform: `scale(${interpolate(p,[0,1],[.72,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})})`}}><div style={{width: 140, height: 140, borderRadius: 26, background: C.blue, boxShadow: "0 0 40px rgba(10,132,255,.75)", display: "flex", alignItems: "center", justifyContent: "center", color: C.white, fontSize: 74, fontWeight: 950}}>A</div><div><div style={{color: C.white, fontSize: 76, fontWeight: 950}}>{cue.section.subtitle}</div><div style={{marginTop: 8, color: C.gold, fontSize: 22, fontWeight: 950, letterSpacing: 6}}>{cue.section.eyebrow}</div></div></div>; };

export const OrderedSequence: React.FC<LayoutEffectProps> = ({cue, props}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); const steps=listProp(cue, props, "steps"); return <div style={{position:"absolute",left:100,top:205,width:760}}><div style={{color:C.gold,fontSize:17,fontWeight:950,letterSpacing:4,marginBottom:18}}>{textProp(props,"categoryTag",cue.section.eyebrow)}</div>{steps.map((row,i) => <div key={row+"-"+i} style={{display:"flex",gap:24,alignItems:"center",marginBottom:22,...enter(f,s+getStaggerStartFrame(fps,i))}}><div style={{color:i===steps.length-1?C.gold:C.blue,fontSize:64,fontWeight:950}}>{("0"+String(i+1)).slice(-2)}</div><Panel color={i===steps.length-1?C.gold:C.blue} style={{flex:1,padding:"18px 22px"}}><div style={{color:C.white,fontSize:32,fontWeight:950}}>{row}</div></Panel></div>)}</div>; };

export const OrgChart: React.FC<LayoutEffectProps> = ({cue}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const line=interpolate(f,[s+16,s+78],[0,260],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const units=rows(cue); return <div style={{position:"absolute",left:135,top:180,width:1030,height:600,...enter(f,s)}}><Panel color={C.gold} style={{position:"absolute",left:390,top:0,width:255,padding:"18px",textAlign:"center"}}><div style={{color:C.white,fontSize:34,fontWeight:950}}>CEO</div><div style={{color:C.gold,fontSize:13,fontWeight:900,letterSpacing:2}}>INTEGRATOR</div></Panel><div style={{position:"absolute",left:515,top:92,width:4,height:line,background:C.gold,boxShadow:"0 0 16px rgba(255,209,102,.9)"}}/><div style={{position:"absolute",left:125,top:350,height:3,width:Math.min(780,line*3),background:C.blue,boxShadow:"0 0 16px rgba(10,132,255,.8)"}}/>{units.map((unit,i)=><Panel key={unit} color={C.blue} style={{position:"absolute",left:15+i*260,top:410,width:220,padding:"18px",textAlign:"center",...enter(f,s+74+i*14,0)}}><div style={{color:C.white,fontSize:28,fontWeight:950}}>{unit}</div><div style={{marginTop:4,color:C.blue,fontSize:12,fontWeight:900}}>FUNCTION TEAM</div></Panel>)}</div>; };

export const DrawLine: React.FC<LayoutEffectProps> = ({cue}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const len=interpolate(f,[s+20,s+130],[0,1000],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); return <div style={{position:"absolute",left:100,top:280,width:1220,...enter(f,s)}}><div style={{color:C.white,fontSize:68,fontWeight:950}}>{cue.section.subtitle}</div><svg viewBox="0 0 1200 260" style={{marginTop:35,width:1200,height:260}}><path d="M40 190 C220 100 360 220 520 140 S830 68 1140 104" fill="none" stroke={C.blue} strokeWidth="8" strokeLinecap="round" strokeDasharray="1200" strokeDashoffset={1200-len}/><circle cx="1140" cy="104" r={len>950?10:0} fill={C.gold}/></svg><div style={{color:C.gold,fontSize:24,fontWeight:950,letterSpacing:3}}>DRAWN ARGUMENT · {cue.caption.zh}</div></div>; };

export const ProgressDonut: React.FC<LayoutEffectProps> = ({cue}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const val=interpolate(f,[s+20,s+100],[0,74],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const dash=2*Math.PI*132; return <div style={{position:"absolute",left:150,top:190,display:"flex",alignItems:"center",gap:68,...enter(f,s)}}><div style={{position:"relative",width:360,height:360}}><svg viewBox="0 0 360 360" style={{width:360,height:360,transform:"rotate(-90deg)"}}><circle cx="180" cy="180" r="132" fill="none" stroke="rgba(255,255,255,.13)" strokeWidth="28"/><circle cx="180" cy="180" r="132" fill="none" stroke={C.blue} strokeWidth="28" strokeLinecap="round" strokeDasharray={dash} strokeDashoffset={dash*(1-val/100)}/></svg><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column"}}><div style={{color:C.white,fontSize:82,fontWeight:950}}>{Math.round(val)}%</div><div style={{color:C.blue,fontSize:16,fontWeight:950,letterSpacing:3}}>COMPLETION</div></div></div><div><div style={{color:C.gold,fontSize:22,fontWeight:950,letterSpacing:4}}>R&D RELEASE</div><div style={{marginTop:18,color:C.white,fontSize:54,fontWeight:950}}>7.5% → 10%</div><div style={{marginTop:15,color:C.dim,fontSize:26,fontWeight:800}}>{cue.caption.zh}</div></div></div>; };

export const BullBear: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const divide=interpolate(f,[s+8,s+46],[50,960],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const bullLabel=textProp(props,"bullLabel","看多观点"); const bullText=textProp(props,"bullText",cue.section.subtitle); const bearLabel=textProp(props,"bearLabel","风险提示"); const bearText=textProp(props,"bearText",cue.caption.zh); return <div style={{position:"absolute",inset:0,...enter(f,s)}}><div style={{position:"absolute",left:90,top:245,width:700,color:C.green}}><div style={{fontSize:22,fontWeight:950,letterSpacing:5}}>{bullLabel}</div><div style={{marginTop:22,color:C.white,fontSize:72,lineHeight:"84px",fontWeight:950}}>{bullText}</div></div><div style={{position:"absolute",right:90,top:245,width:700,color:C.red,textAlign:"right"}}><div style={{fontSize:22,fontWeight:950,letterSpacing:5}}>{bearLabel}</div><div style={{marginTop:22,color:C.white,fontSize:72,lineHeight:"84px",fontWeight:950}}>{bearText}</div></div><div style={{position:"absolute",left:divide,top:176,bottom:190,width:3,background:C.gold,boxShadow:"0 0 24px rgba(255,209,102,.9)"}}/></div>; };

export const OpinionHero: React.FC<LayoutEffectProps> = ({cue}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const p=spring({frame:f-s-18,fps,config:{damping:11,stiffness:170}}); return <div style={{position:"absolute",left:120,right:120,top:255,textAlign:"center",transform:`scale(${interpolate(p,[0,1],[.64,1.04],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})})`}}><div style={{color:C.gold,fontSize:22,fontWeight:950,letterSpacing:5}}>THE VIEW</div><div style={{marginTop:18,color:C.white,fontSize:102,lineHeight:"118px",fontWeight:950,textShadow:"0 0 42px rgba(10,132,255,.82)"}}>{cue.section.subtitle}</div><div style={{marginTop:24,color:C.blue,fontSize:35,fontWeight:900}}>{cue.caption.zh}</div></div>; };

export const PhotoWall: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const labels=listProp(cue, props, "items"); const xs=[0,340,670,935]; const ys=[95,0,170,65]; return <div style={{position:"absolute",left:120,top:170,width:1250,height:650}}>{labels.map((label,i)=><Panel key={label} color={[C.blue,C.gold,C.green,C.blue][i]} style={{position:"absolute",left:xs[i],top:ys[i],width:300,height:380,padding:22,rotate:`${[-5,4,-2,5][i]}deg`,...enter(f,s+getStaggerStartFrame(fps,i),i%2?26:-26)}}><div style={{height:250,background:"linear-gradient(145deg, #c2ccd7, #253244)",borderRadius:6,boxShadow:"inset 0 0 40px rgba(10,132,255,.24)"}}/><div style={{marginTop:20,color:C.white,fontSize:30,fontWeight:950}}>{label}</div><div style={{marginTop:4,color:C.dim,fontSize:13,fontWeight:900,letterSpacing:2}}>PRODUCT HISTORY</div></Panel>)}</div>; };

export const ProductExplosion: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const p=interpolate(f,[s+20,s+96],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const labels=listProp(cue,props,"items").slice(0,4); const offsets=[[-250,-125],[220,-118],[-240,225],[230,230]]; return <div style={{position:"absolute",left:250,top:180,width:1200,height:650,...enter(f,s)}}><div style={{position:"absolute",left:430,top:220,width:260,height:160,background:"#BFCAD6",borderRadius:14}}/>{labels.map((label,i)=><Panel key={label} color={[C.blue,C.gold,C.green,C.blue][i]} style={{position:"absolute",left:500+(offsets[i]?.[0] ?? 0)*p,top:260+(offsets[i]?.[1] ?? 0)*p,padding:"15px 18px",...enter(f,s+getStaggerStartFrame(fps,i),0)}}><div style={{color:C.white,fontSize:24,fontWeight:950}}>{label}</div></Panel>)}<div style={{position:"absolute",left:300,top:535,color:C.white,fontSize:38,fontWeight:950}}>{cue.section.subtitle}</div></div>; };

export const NewspaperSwap: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const shift=interpolate(f,[s+28,s+96],[440,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const oldHeadline=textProp(props,"oldHeadline",resolveContentText(cue,props)); const newHeadline=textProp(props,"newHeadline",cue.section.subtitle); return <div style={{position:"absolute",left:120,top:180,width:1260,height:650,...enter(f,s)}}><Panel color={C.dim} style={{position:"absolute",left:0,top:45,width:650,padding:"32px",opacity:.44}}><div style={{color:C.dim,fontSize:18,fontWeight:950,letterSpacing:4}}>{textProp(props,"oldLabel",cue.section.eyebrow)}</div><div style={{marginTop:24,color:C.white,fontSize:58,lineHeight:"70px",fontWeight:950}}>{oldHeadline}</div></Panel><Panel color={C.blue} style={{position:"absolute",left:550+shift,top:150,width:690,padding:"34px"}}><div style={{color:C.blue,fontSize:18,fontWeight:950,letterSpacing:4}}>{textProp(props,"newLabel",cue.section.eyebrow)}</div><div style={{marginTop:22,color:C.white,fontSize:58,lineHeight:"70px",fontWeight:950}}>{newHeadline}</div><div style={{marginTop:18,color:C.gold,fontSize:24,fontWeight:950}}>{textProp(props,"footer",cue.caption.zh)}</div></Panel></div>; };

export const RouteMap: React.FC<LayoutEffectProps> = ({cue}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const draw=interpolate(f,[s+22,s+116],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const nodes=[[170,355,"ORIGIN",C.gold],[960,310,"PROCESS",C.blue],[1270,190,"SIGNAL",C.green]]; return <div style={{position:"absolute",left:150,top:165,width:1400,height:650,...enter(f,s)}}><svg viewBox="0 0 1400 650" style={{width:1400,height:650}}><path d="M170 355 C410 100 720 135 960 310 S1180 470 1270 190" stroke={C.blue} strokeWidth="7" fill="none" strokeDasharray="1500" strokeDashoffset={1500-draw*1500}/>{nodes.map(([x,y,label,color])=><g key={label as string}><circle cx={x as number} cy={y as number} r="18" fill={color as string}/><text x={(x as number)+27} y={(y as number)+8} fill="white" fontSize="26" fontWeight="900">{label}</text></g>)}</svg><div style={{position:"absolute",left:80,top:65,color:C.white,fontSize:48,fontWeight:950}}>{cue.section.subtitle}</div></div>; };

export const ScreenRecording: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const x=interpolate(f,[s+34,s+124],[230,730],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const items=listProp(cue,props,"items").slice(0,3); return <Panel color={C.blue} style={{position:"absolute",left:135,top:145,width:1290,height:700,padding:0,overflow:"hidden",...enter(f,s)}}><div style={{height:52,background:"rgba(255,255,255,.08)"}}/><div style={{padding:34}}><div style={{color:C.white,fontSize:46,fontWeight:950}}>{textProp(props,"headline",cue.section.subtitle)}</div><div style={{marginTop:34,display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:18}}>{items.map((item,i)=><Panel key={item} color={[C.gold,C.green,C.blue][i]} style={{padding:22,...enter(f,s+getStaggerStartFrame(fps,i),0)}}><div style={{color:C.white,fontSize:26,fontWeight:950}}>{item}</div></Panel>)}</div></div><div style={{position:"absolute",left:x,top:390,width:0,height:0,borderLeft:"18px solid transparent",borderRight:"18px solid transparent",borderBottom:"34px solid white",transform:"rotate(45deg)"}}/></Panel>; };

export const DesktopFolders: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const folders=listProp(cue,props,"items").slice(0,4); return <div style={{position:"absolute",left:140,top:190,display:"grid",gridTemplateColumns:"repeat(2, 330px)",gap:36,...enter(f,s)}}>{folders.map((folder,i)=><div key={folder} style={{...enter(f,s+getStaggerStartFrame(fps,i),0),textAlign:"center"}}><div style={{width:240,height:165,margin:"auto",borderRadius:"10px 10px 16px 16px",background:i%2?C.gold:C.blue}}/><div style={{marginTop:16,color:C.white,fontSize:25,fontWeight:950}}>{folder}</div></div>)}</div>; };

export const TimeRewind: React.FC<LayoutEffectProps> = ({cue}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const p=interpolate(f,[s+20,s+122],[1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); return <div style={{position:"absolute",left:120,right:120,top:300,...enter(f,s)}}><div style={{color:C.gold,fontSize:22,fontWeight:950,letterSpacing:5}}>REWIND</div><div style={{marginTop:22,position:"relative",height:90}}><div style={{position:"absolute",left:0,right:0,top:37,height:5,background:"rgba(255,255,255,.2)"}}/><div style={{position:"absolute",left:`${p*100}%`,top:22,width:34,height:34,borderRadius:"50%",background:C.gold,transform:"translateX(-50%)",boxShadow:"0 0 20px rgba(255,209,102,.9)"}}/>{["2026","2021","2019","2011","2001"].map((year,i)=><div key={year} style={{position:"absolute",left:`${i*25}%`,top:52,color:C.white,fontSize:22,fontWeight:950,transform:"translateX(-50%)"}}>{year}</div>)}</div><div style={{marginTop:36,color:C.white,fontSize:65,fontWeight:950}}>{cue.section.subtitle}</div></div>; };

export const ClipboardNote: React.FC<LayoutEffectProps> = ({cue}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); return <Panel color={C.gold} style={{position:"absolute",left:175,top:185,width:760,minHeight:560,padding:"48px 54px",background:"rgba(28,25,15,.88)",...enter(f,s)}}><div style={{position:"absolute",left:270,top:-22,width:260,height:44,borderRadius:7,background:"#B6BDC6"}}/><div style={{color:C.gold,fontSize:18,fontWeight:950,letterSpacing:4}}>DECISION NOTE</div><div style={{marginTop:28,color:C.white,fontSize:48,lineHeight:"62px",fontWeight:950}}>{cue.section.subtitle}</div><div style={{marginTop:30,color:C.dim,fontSize:28,lineHeight:"42px"}}>{cue.caption.zh}</div><div style={{marginTop:34,borderTop:"2px solid rgba(255,209,102,.55)",width:interpolate(f,[s+50,s+110],[0,560],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}}/></Panel>; };

export const ClosingChecklist: React.FC<LayoutEffectProps> = ({cue, props}) => {
  const f = useCurrentFrame();
  const {fps} = useVideoConfig();
  const s = startFrame(cue, fps);
  const boxColor = boxColorProp(props);
  const items = listProp(cue, props, "items").slice(0, 4);
  return <div style={{position: "absolute", left: 120, top: 175, width: 760, ...enter(f, s)}}>
    <div style={{color: C.gold, fontSize: 17, fontWeight: 950, letterSpacing: 4}}>{cue.section.eyebrow}</div>
    <div style={{marginTop: 16, color: C.white, fontSize: 56, lineHeight: "66px", fontWeight: 950}}>{textProp(props, "title", cue.section.subtitle)}</div>
    <div style={{marginTop: 26, display: "flex", flexDirection: "column", gap: 14}}>{items.map((row, i) => <Panel key={row+"-"+i} color={boxColor} style={{padding: "16px 20px", display: "flex", alignItems: "center", gap: 16, ...enter(f, s + getStaggerStartFrame(fps, i))}}><Mark value="✓" color={boxColor}/><div style={{color: C.white, fontSize: 31, fontWeight: 950}}>{row}</div></Panel>)}</div>
    <div style={{marginTop: 22, color: C.blue, fontSize: 24, fontWeight: 950}}>{cue.caption.zh}</div>
  </div>;
};

