import React from "react";
import {Easing, interpolate, spring, useCurrentFrame, useVideoConfig} from "remotion";
import type {JasonWuCue} from "./timeline";
import type {LayoutEffectProps} from "./DemoEffectComponents";
import {getStaggerStartFrame, resolveContentItems, resolveContentText} from "./layoutRuntime";

const C = {blue: "#0A84FF", gold: "#FFD166", green: "#38D7A6", red: "#FF5B5B", white: "#FFFFFF", dim: "rgba(255,255,255,.58)", panel: "var(--card-panel)"};
const ease = Easing.bezier(.16, 1, .3, 1);
const BODY_TOP = 300;
const startFrame = (cue: JasonWuCue, fps: number) => Math.round(cue.start * fps) + 8;
const enter = (frame: number, start: number, x = -28) => ({opacity: interpolate(frame, [start, start + 24], [0, 1], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease}), transform: `translateX(${interpolate(frame, [start, start + 24], [x, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease})}px)`});
const Panel: React.FC<{children: React.ReactNode; color?: string; style?: React.CSSProperties}> = ({children, color = C.blue, style}) => <div style={{background: C.panel, border: `1px solid ${color}`, borderRadius: 10, boxShadow: `0 0 28px color-mix(in srgb, ${color} 25%, transparent)`, ...style}}>{children}</div>;
const Mark: React.FC<{value: string; color: string}> = ({value, color}) => <div style={{width: 46, height: 46, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", color, fontSize: 33, fontWeight: 950, border: `2px solid ${color}`, boxShadow: `0 0 18px color-mix(in srgb, ${color} 70%, transparent)`}}>{value}</div>;
const textProp = (props: Record<string, unknown> | undefined, key: string, fallback: string) => typeof props?.[key] === "string" ? String(props[key]) : fallback;
const itemLimit = (props: Record<string, unknown> | undefined, fallback = 4) => Math.max(1, Math.min(8, Math.round(Number((props?.designTokens as Record<string, unknown> | undefined)?.defaultItemCount) || fallback)));
const listProp = (cue: JasonWuCue, props: Record<string, unknown> | undefined, key: string) => resolveContentItems(cue, props, [key, "items", "steps", "units", "comments", "nodes", "years"]);
const listItems = (cue: JasonWuCue, props: Record<string, unknown> | undefined, key: string, fallback = 4) => { const rows = listProp(cue, props, key); return rows.slice(0, Math.min(8, Math.max(itemLimit(props, fallback), rows.length))); };
const optionalStrings = (value: unknown) => Array.isArray(value) ? value.map((item) => typeof item === "string" ? item.trim() : "").filter(Boolean) : [];
const rows = (cue: JasonWuCue, props?: Record<string, unknown>) => resolveContentItems(cue, props, ["items", "steps", "units", "comments"]);
const boxColors: Record<string, string> = {purple: "#8B5CF6", blue: "#0A84FF", gold: "#FFD166", white: "#F8FAFC", green: "#36D399", red: "#FF6B6B"};
const boxColorProp = (props: Record<string, unknown> | undefined, fallback = C.blue) => boxColors[textProp(props, "boxColor", "auto")] ?? fallback;

export const RejectList: React.FC<LayoutEffectProps> = ({cue, props}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); const items = rows(cue, props).slice(0, itemLimit(props, 4)); const subtitles = optionalStrings(props?.itemSubtitles ?? props?.subLabels); const fallbackSubtitle = textProp(props, "subLabel", ""); return <div style={{position: "absolute", left: 98, top: BODY_TOP, width: 740, ...enter(f, s)}}><div style={{color: C.red, fontSize: 22, fontWeight: 950, letterSpacing: 3}}>{textProp(props, "title", "REJECTED PATHS")}</div><div style={{marginTop: 22, display: "flex", flexDirection: "column", gap: 14}}>{items.map((row, i) => { const subtitle = subtitles[i] ?? fallbackSubtitle; return <Panel key={row+"-"+i} color={C.red} style={{padding: "18px 22px", display: "flex", alignItems: "center", gap: 18, ...enter(f, s + 16 + i * 18)}}><Mark value="×" color={C.red}/><div style={{minWidth: 0}}><div style={{color: C.white, fontSize: 30, lineHeight: "36px", fontWeight: 950, overflowWrap: "break-word"}}>{row}</div>{subtitle ? <div style={{marginTop: 5, color: "#FF9DA8", fontSize: 14, lineHeight: "18px", fontWeight: 900, letterSpacing: 2, overflowWrap: "break-word"}}>{subtitle}</div> : null}</div></Panel>; })}</div></div>; };

export const CheckProgress: React.FC<LayoutEffectProps> = ({cue, props}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); const title=textProp(props,"bodyText",textProp(props,"body",textProp(props,"title","PRODUCT RECOVERY"))); const target=Number(props?.progress ?? props?.value ?? 82); const safeTarget=Number.isFinite(target)?Math.max(0,Math.min(100,target)):82; const p = interpolate(f, [s + 20, s + 132], [0, safeTarget], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease}); const sourceRows=rows(cue, props); const items=sourceRows.slice(0, Math.min(8, Math.max(itemLimit(props, 3), sourceRows.length))); return <div style={{position: "absolute", left: 96, top: BODY_TOP, width: 710, ...enter(f, s)}}><div style={{display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: 24}}><div style={{color: C.white, fontSize: 43, fontWeight: 950, overflowWrap: "anywhere"}}>{title}</div><div style={{color: C.green, fontSize: 44, fontWeight: 950, flex: "0 0 auto"}}>{Math.round(p)}</div></div><div style={{height: 22, marginTop: 18, background: "rgba(255,255,255,.12)", overflow: "hidden", borderRadius: 99}}><div style={{width: `${p}%`, height: "100%", background: C.green, boxShadow: "0 0 20px rgba(54,211,153,.9)"}}/></div><div style={{marginTop: 28, display: "flex", flexDirection: "column", gap: 13}}>{items.map((row, i) => <div key={row} style={{display: "flex", alignItems: "center", gap: 16, margin: "12px 0", color: C.white, fontSize: 33, fontWeight: 900, ...enter(f, s + 36 + i * 18)}}><Mark value="✓" color={C.green}/>{row}</div>)}</div></div>; };

export const DiagonalChips: React.FC<LayoutEffectProps> = ({cue, props}) => {
  const f = useCurrentFrame();
  const {fps} = useVideoConfig();
  const s = startFrame(cue, fps);
  const designTokens = props?.designTokens && typeof props.designTokens === "object" ? props.designTokens as Record<string, unknown> : {};
  const gap = Math.max(0, Math.min(80, Number(designTokens.gap) || 8));
  const defaultItemCount = Math.max(1, Math.min(8, Math.round(Number(designTokens.defaultItemCount) || 4)));
  const staggerFrames = Math.max(0, Math.min(45, Math.round(Number(designTokens.staggerFrames) || Math.round(fps * 0.5))));
  const chips = listProp(cue, props, "items").slice(0, defaultItemCount);
  return <div style={{position: "absolute", left: 120, top: BODY_TOP, width: 720, display: "flex", flexDirection: "column", gap}}>{chips.map((chip, i) => {
    const start = s + Math.round(fps * 0.5) + i * staggerFrames;
    const progress = interpolate(f, [start, start + 32], [0, 1], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease});
    const x = interpolate(progress, [0, 1], [-280, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp"});
    const y = interpolate(progress, [0, 1], [38, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp"});
    const color = [C.blue, C.gold, C.green][i % 3];
    return <div key={chip+"-"+i} style={{paddingLeft: i * 34, opacity: progress, transform: "translate3d("+x+"px,"+y+"px,0)", willChange: "transform, opacity"}}><Panel color={color} style={{width: 560, height: 104, boxSizing: "border-box", padding: "16px 24px", clipPath: "polygon(5% 0,100% 0,95% 100%,0 100%)"}}><div style={{color, fontSize: 14, fontWeight: 950, letterSpacing: 4}}>CHIP / {("0" + String(i + 1)).slice(-2)}</div><div style={{marginTop: 7, color: C.white, fontSize: 30, fontWeight: 950}}>{chip}</div></Panel></div>;
  })}</div>;
};

export const FloatingChips: React.FC<LayoutEffectProps> = ({cue, props}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); const chips = listProp(cue, props, "items").slice(0, 4); const pos = [[145,250],[530,190],[275,525],[750,485]]; return <div style={{position: "absolute", inset: 0}}>{chips.map((chip, i) => { const color = [C.blue, C.gold, C.green, C.blue][i]; return <Panel key={chip} color={color} style={{position: "absolute", left: pos[i]?.[0] ?? 145, top: (pos[i]?.[1] ?? 250) + Math.sin((f - s) / 17 + i) * 12, padding: "18px 22px", ...enter(f, s + getStaggerStartFrame(fps, i), i % 2 ? 34 : -34)}}><div style={{color: C.white, fontSize: 29, fontWeight: 950}}>{chip}</div></Panel>; })}</div>; };

export const BareTypography: React.FC<LayoutEffectProps> = ({cue}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); return <div style={{position: "absolute", left: 110, right: 130, top: BODY_TOP, ...enter(f, s, -42)}}><div style={{width: interpolate(f, [s + 18, s + 70], [0, 164], {extrapolateLeft: "clamp", extrapolateRight: "clamp"}), height: 6, background: C.gold}}/><div style={{marginTop: 28, color: C.white, fontSize: 82, lineHeight: "96px", fontWeight: 950, maxWidth: 1160}}>{cue.section.subtitle}</div><div style={{marginTop: 26, color: C.blue, fontSize: 25, fontWeight: 950, letterSpacing: 5}}>{cue.section.eyebrow}</div><div style={{marginTop: 20, color: C.dim, fontSize: 32, lineHeight: "46px", maxWidth: 900}}>{cue.caption.zh}</div></div>; };

export const ChapterCard: React.FC<LayoutEffectProps> = ({cue, props}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); const body = textProp(props,"body",textProp(props,"effectText",cue.caption.zh)); const quote = textProp(props,"highlightQuote",""); return <Panel color={C.blue} style={{position: "absolute", left: 112, top: BODY_TOP, width: 760, padding: "34px 40px", ...enter(f, s)}}><div style={{color: C.blue, fontSize: 18, fontWeight: 950, letterSpacing: 5}}>CHAPTER / {cue.section.eyebrow}</div><div style={{marginTop: 20, color: C.white, fontSize: 55, lineHeight: "67px", fontWeight: 950}}>{body}</div>{quote&&<div style={{marginTop: 14, color: C.gold, fontSize: 23, lineHeight: "32px", fontWeight: 950}}>{quote}</div>}</Panel>; };

export const LogoWordmark: React.FC<LayoutEffectProps> = ({cue, props}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); const p = spring({frame: f - s, fps, config: {damping: 13, stiffness: 150}}); const body = textProp(props, "body", textProp(props, "bodyText", textProp(props, "effectText", cue.caption.zh || cue.section.subtitle))); const quote = textProp(props, "highlightQuote", cue.section.eyebrow); const mark = textProp(props, "mark", "A").slice(0, 2); return <div style={{position: "absolute", left: 125, top: BODY_TOP, display: "flex", alignItems: "center", gap: 32, ...enter(f, s), transform: `scale(${interpolate(p,[0,1],[.72,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})})`}}><div style={{width: 140, height: 140, borderRadius: 26, background: C.blue, boxShadow: "0 0 40px rgba(10,132,255,.75)", display: "flex", alignItems: "center", justifyContent: "center", color: C.white, fontSize: 74, fontWeight: 950}}>{mark}</div><div style={{maxWidth: 820}}><div style={{color: C.white, fontSize: 76, lineHeight: "88px", fontWeight: 950, overflowWrap: "break-word"}}>{body}</div>{quote ? <div style={{marginTop: 8, color: C.gold, fontSize: 22, lineHeight: "30px", fontWeight: 950, letterSpacing: 6, overflowWrap: "break-word"}}>{quote}</div> : null}</div></div>; };

export const OrderedSequence: React.FC<LayoutEffectProps> = ({cue, props}) => { const f = useCurrentFrame(); const {fps} = useVideoConfig(); const s = startFrame(cue, fps); const steps=listProp(cue, props, "steps"); return <div className="animated-content-slot" style={{position:"absolute",left:100,top:BODY_TOP,width:760}}>{steps.map((row,i) => <div key={row+"-"+i} style={{display:"flex",gap:24,alignItems:"center",marginBottom:22,...enter(f,s+getStaggerStartFrame(fps,i))}}><div style={{color:i===steps.length-1?C.gold:C.blue,fontSize:64,fontWeight:950}}>{("0"+String(i+1)).slice(-2)}</div><Panel color={i===steps.length-1?C.gold:C.blue} style={{flex:1,padding:"18px 22px"}}><div style={{color:C.white,fontSize:32,fontWeight:950}}>{row}</div></Panel></div>)}</div>; };

export const OrgChart: React.FC<LayoutEffectProps> = ({cue}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const line=interpolate(f,[s+16,s+78],[0,260],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const units=rows(cue); return <div style={{position:"absolute",left:135,top:BODY_TOP,width:1030,height:600,...enter(f,s)}}><Panel color={C.gold} style={{position:"absolute",left:390,top:0,width:255,padding:"18px",textAlign:"center"}}><div style={{color:C.white,fontSize:34,fontWeight:950}}>CEO</div><div style={{color:C.gold,fontSize:13,fontWeight:900,letterSpacing:2}}>INTEGRATOR</div></Panel><div style={{position:"absolute",left:515,top:92,width:4,height:line,background:C.gold,boxShadow:"0 0 16px rgba(255,209,102,.9)"}}/><div style={{position:"absolute",left:125,top:350,height:3,width:Math.min(780,line*3),background:C.blue,boxShadow:"0 0 16px rgba(10,132,255,.8)"}}/>{units.map((unit,i)=><Panel key={unit} color={C.blue} style={{position:"absolute",left:15+i*260,top:410,width:220,padding:"18px",textAlign:"center",...enter(f,s+74+i*14,0)}}><div style={{color:C.white,fontSize:28,fontWeight:950}}>{unit}</div><div style={{marginTop:4,color:C.blue,fontSize:12,fontWeight:900}}>FUNCTION TEAM</div></Panel>)}</div>; };

export const DrawLine: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const len=interpolate(f,[s+20,s+130],[0,1000],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const bodyText=textProp(props,"bodyText",textProp(props,"body",textProp(props,"effectText",textProp(props,"text",cue.section.subtitle)))); const subText=textProp(props,"highlightQuote",textProp(props,"annotation",textProp(props,"subLabel",cue.caption.zh))); return <div style={{position:"absolute",left:100,top:BODY_TOP,width:1220,...enter(f,s)}}><div style={{color:C.white,fontSize:68,fontWeight:950,overflowWrap:"break-word"}}>{bodyText}</div><svg viewBox="0 0 1200 260" style={{marginTop:35,width:1200,height:260}}><path d="M40 190 C220 100 360 220 520 140 S830 68 1140 104" fill="none" stroke={C.blue} strokeWidth="8" strokeLinecap="round" strokeDasharray="1200" strokeDashoffset={1200-len}/><circle cx="1140" cy="104" r={len>950?10:0} fill={C.gold}/></svg><div style={{color:C.blue,fontSize:24,fontWeight:950,letterSpacing:3,overflowWrap:"break-word"}}>{subText}</div></div>; };

export const ProgressDonut: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const target=Math.max(0,Math.min(100,Number(props?.value ?? props?.progress ?? 74)||74)); const val=interpolate(f,[s+20,s+100],[0,target],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const dash=2*Math.PI*132; const subtitle=textProp(props,"metric",textProp(props,"label",cue.section.eyebrow)); const bodyText=textProp(props,"bodyText",textProp(props,"unit",cue.section.subtitle)); return <div style={{position:"absolute",left:150,top:BODY_TOP,display:"flex",alignItems:"center",gap:68,...enter(f,s)}}><div style={{position:"relative",width:360,height:360}}><svg viewBox="0 0 360 360" style={{width:360,height:360,transform:"rotate(-90deg)"}}><circle cx="180" cy="180" r="132" fill="none" stroke="rgba(255,255,255,.13)" strokeWidth="28"/><circle cx="180" cy="180" r="132" fill="none" stroke={C.blue} strokeWidth="28" strokeLinecap="round" strokeDasharray={dash} strokeDashoffset={dash*(1-val/100)}/></svg><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{color:C.white,fontSize:82,fontWeight:950}}>{Math.round(val)}%</div></div></div><div><div style={{color:C.gold,fontSize:22,fontWeight:950,letterSpacing:4}}>{subtitle}</div><div style={{marginTop:18,color:C.white,fontSize:54,fontWeight:950}}>{bodyText}</div></div></div>; };

export const BullBear: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const divide=interpolate(f,[s+8,s+46],[50,960],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const bullLabel=textProp(props,"bullLabel","看多观点"); const bullText=textProp(props,"bullText",textProp(props,"body",textProp(props,"effectText",cue.section.subtitle))); const bearLabel=textProp(props,"bearLabel","风险提示"); const bearText=textProp(props,"bearText",cue.caption.zh); const footer=textProp(props,"highlightQuote",""); const textStyle={marginTop:22,color:C.white,fontSize:56,lineHeight:"66px",fontWeight:950,overflowWrap:"break-word" as const}; return <div style={{position:"absolute",inset:0,...enter(f,s)}}><div style={{position:"absolute",left:90,top:BODY_TOP,width:650,color:C.green}}><div style={{fontSize:22,fontWeight:950,letterSpacing:5}}>{bullLabel}</div><div style={textStyle}>{bullText}</div></div><div style={{position:"absolute",right:90,top:BODY_TOP,width:650,color:C.red,textAlign:"right"}}><div style={{fontSize:22,fontWeight:950,letterSpacing:5}}>{bearLabel}</div><div style={textStyle}>{bearText}</div></div><div style={{position:"absolute",left:divide,top:176,bottom:190,width:3,background:C.gold,boxShadow:"0 0 24px rgba(255,209,102,.9)"}}/>{footer&&<div style={{position:"absolute",left:180,right:180,bottom:138,color:C.gold,fontSize:32,lineHeight:"42px",fontWeight:950,textAlign:"center",textShadow:"0 0 22px rgba(255,209,102,.45)"}}>{footer}</div>}</div>; };

export const OpinionHero: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const p=spring({frame:f-s-18,fps,config:{damping:11,stiffness:170}}); const body = textProp(props,"body",textProp(props,"effectText",cue.caption.zh)); const quote = textProp(props,"highlightQuote",cue.section.subtitle); const designTokens = props?.designTokens && typeof props.designTokens === "object" ? props.designTokens as Record<string, unknown> : {}; const contentScale=Number(designTokens.contentScale)||1; return <div style={{position:"absolute",left:120,right:120,top:BODY_TOP,textAlign:"center",transform:`scale(${contentScale*interpolate(p,[0,1],[.64,1.04],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})})`}}><div style={{color:C.gold,fontSize:22,fontWeight:950,letterSpacing:5}}>THE VIEW</div><div style={{marginTop:18,color:C.white,fontSize:102,lineHeight:"118px",fontWeight:950,textShadow:"0 0 42px rgba(10,132,255,.82)"}}>{body}</div><div style={{marginTop:24,color:C.blue,fontSize:35,fontWeight:900}}>{quote}</div></div>; };

export const PhotoWall: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const fallback=listProp(cue, props, "items"); const exact=(key:string,fallbackValue:string)=>typeof props?.[key] === "string" ? String(props?.[key]) : fallbackValue; const cards=[0,1,2,3].map((_,i)=>{const n=i+1; const title=exact(`photoTitle${n}`,fallback[i] ?? ["核心信息","视觉节奏","行动结论","补充证据"][i]); const subtitle=exact(`photoSubtitle${n}`,["PRODUCT HISTORY","VISUAL RHYTHM","ACTION SIGNAL","EXTRA PROOF"][i]); const photo=typeof props?.[`photo${n}`] === "string" ? String(props?.[`photo${n}`]) : ""; return {title,subtitle,photo};}).filter((card)=>card.title.trim() || card.photo).slice(0,4); const xs=[0,300,600,900]; const ys=[92,0,166,64]; const colors=[C.blue,C.gold,C.green,C.blue]; return <div style={{position:"absolute",left:120,top:BODY_TOP,width:1210,height:650}}>{cards.map((card,i)=><Panel key={card.title+"-"+i} color={colors[i]} style={{position:"absolute",left:xs[i],top:ys[i],width:278,height:362,padding:18,rotate:`${[-5,4,-2,5][i]}deg`,...enter(f,s+getStaggerStartFrame(fps,i),i%2?24:-24)}}><div style={{height:228,background:card.photo?`center / cover no-repeat url(${card.photo})`:"linear-gradient(145deg, #c2ccd7, #253244)",borderRadius:6,boxShadow:"inset 0 0 40px rgba(10,132,255,.24), 0 0 20px rgba(10,132,255,.16)"}}/><div style={{marginTop:18,color:C.white,fontSize:27,lineHeight:"32px",fontWeight:950,overflowWrap:"break-word"}}>{card.title}</div>{card.subtitle?<div style={{marginTop:5,color:C.dim,fontSize:12,lineHeight:"15px",fontWeight:900,letterSpacing:2,overflowWrap:"break-word"}}>{card.subtitle}</div>:null}</Panel>)}</div>; };

export const ProductExplosion: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const fallbackLabels=listProp(cue,props,"items").slice(0,4); const labels=[1,2,3,4].map((n,i)=>textProp(props,"productTitle"+String(n),fallbackLabels[i] ?? "")).filter(Boolean).slice(0,4); const centerImage=textProp(props,"centerImage",textProp(props,"productImage","")); const centerLabel=textProp(props,"centerLabel","APPLE ECOSYSTEM"); const slots=labels.map((label,i)=>({label,image:textProp(props,"productImage"+String(i+1),"")})); const positions=[[-310,-165],[315,-165],[-310,178],[315,178]]; return <div style={{position:"absolute",left:185,top:BODY_TOP,width:1180,height:620}}><div style={{position:"absolute",left:420,top:162,width:340,height:230,borderRadius:34,background:"linear-gradient(145deg, rgba(255,255,255,.96), rgba(207,218,232,.78))",border:"1px solid rgba(255,255,255,.84)",boxShadow:"0 24px 60px rgba(0,0,0,.36), 0 0 42px rgba(10,132,255,.22)",display:"grid",placeItems:"center",overflow:"hidden",...enter(f,s,0)}}>{centerImage?<img src={centerImage} style={{width:"100%",height:"100%",objectFit:"contain",padding:34,boxSizing:"border-box"}}/>:<div style={{color:"#111827",fontSize:38,fontWeight:950,letterSpacing:2,textAlign:"center"}}>{centerLabel}</div>}</div>{slots.map((slot,i)=>{const [x,y]=positions[i] ?? [0,0]; const p=spring({frame:f-s-16-i*10,fps,config:{damping:14,stiffness:130}}); const scale=interpolate(p,[0,1],[.62,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}); const accent=[C.blue,C.gold,C.green,C.red][i] ?? C.blue; return <div key={slot.label+String(i)} style={{position:"absolute",left:590+x,top:277+y,width:172,height:172,marginLeft:-86,marginTop:-86,borderRadius:"50%",background:"rgba(7,14,26,.88)",border:"2px solid "+accent,boxShadow:"0 0 30px "+accent+"66, inset 0 0 28px rgba(255,255,255,.08)",display:"grid",placeItems:"center",opacity:Math.min(1,p),transform:"scale("+scale+")",overflow:"hidden"}}>{slot.image?<img src={slot.image} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<div style={{padding:18,color:C.white,fontSize:24,lineHeight:"30px",fontWeight:950,textAlign:"center",overflowWrap:"break-word"}}>{slot.label}</div>}<div style={{position:"absolute",left:12,right:12,bottom:12,padding:"6px 8px",borderRadius:999,background:"rgba(2,6,12,.72)",color:C.white,fontSize:16,lineHeight:"20px",fontWeight:900,textAlign:"center",backdropFilter:"blur(8px)",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{slot.label}</div></div>})}</div>; };

export const NewspaperSwap: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const shift=interpolate(f,[s+28,s+96],[440,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const oldHeadline=textProp(props,"oldHeadline",resolveContentText(cue,props)); const newHeadline=textProp(props,"newHeadline",cue.section.subtitle); return <div style={{position:"absolute",left:120,top:BODY_TOP,width:1260,height:650,...enter(f,s)}}><Panel color={C.dim} style={{position:"absolute",left:0,top:45,width:650,padding:"32px",opacity:.44}}><div style={{color:C.dim,fontSize:18,fontWeight:950,letterSpacing:4}}>{textProp(props,"oldLabel",cue.section.eyebrow)}</div><div style={{marginTop:24,color:C.white,fontSize:58,lineHeight:"70px",fontWeight:950}}>{oldHeadline}</div></Panel><Panel color={C.blue} style={{position:"absolute",left:550+shift,top:150,width:690,padding:"34px"}}><div style={{color:C.blue,fontSize:18,fontWeight:950,letterSpacing:4}}>{textProp(props,"newLabel",cue.section.eyebrow)}</div><div style={{marginTop:22,color:C.white,fontSize:58,lineHeight:"70px",fontWeight:950}}>{newHeadline}</div><div style={{marginTop:18,color:C.gold,fontSize:24,fontWeight:950}}>{textProp(props,"footer",cue.caption.zh)}</div></Panel></div>; };

export const RouteMap: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const draw=interpolate(f,[s+22,s+116],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const labels=listProp(cue, props, "nodes").slice(0, 3); const points=[[170,355,C.gold],[960,310,C.blue],[1270,190,C.green]]; return <div style={{position:"absolute",left:150,top:BODY_TOP,width:1400,height:650,...enter(f,s)}}><svg viewBox="0 0 1400 650" style={{width:1400,height:650}}><path d="M170 355 C410 100 720 135 960 310 S1180 470 1270 190" stroke={C.blue} strokeWidth="7" fill="none" strokeDasharray="1500" strokeDashoffset={1500-draw*1500}/>{labels.map((label,index)=>{const point=points[index];if(!point)return null;const [x,y,color]=point;return <g key={label+"-"+index}><circle cx={x as number} cy={y as number} r="18" fill={color as string}/><text x={(x as number)+27} y={(y as number)+8} fill="white" fontSize="26" fontWeight="900">{label}</text></g>;})}</svg><div style={{position:"absolute",left:80,top:65,color:C.white,fontSize:48,fontWeight:950}}>{cue.section.subtitle}</div></div>; };

export const ScreenRecording: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const x=interpolate(f,[s+34,s+124],[230,730],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const items=listProp(cue,props,"items").slice(0,3); return <Panel color={C.blue} style={{position:"absolute",left:135,top:BODY_TOP,width:1290,height:700,padding:0,overflow:"hidden",...enter(f,s)}}><div style={{height:52,background:"rgba(255,255,255,.08)"}}/><div style={{padding:34}}><div style={{color:C.white,fontSize:46,fontWeight:950}}>{textProp(props,"headline",cue.section.subtitle)}</div><div style={{marginTop:34,display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:18}}>{items.map((item,i)=><Panel key={item} color={[C.gold,C.green,C.blue][i]} style={{padding:22,...enter(f,s+getStaggerStartFrame(fps,i),0)}}><div style={{color:C.white,fontSize:26,fontWeight:950}}>{item}</div></Panel>)}</div></div><div style={{position:"absolute",left:x,top:390,width:0,height:0,borderLeft:"18px solid transparent",borderRight:"18px solid transparent",borderBottom:"34px solid white",transform:"rotate(45deg)"}}/></Panel>; };

const folderPalettes = [
  {tabFrom:"#C9EEFF",tabTo:"#83D1FF",bodyFrom:"#AEE2FF",bodyMid:"#5EB8FF",bodyTo:"#2F86E8",glow:"#5EB8FF"},
  {tabFrom:"#E9D5FF",tabTo:"#C084FC",bodyFrom:"#DDD6FE",bodyMid:"#A78BFA",bodyTo:"#7C3AED",glow:"#A78BFA"},
  {tabFrom:"#CCFBF1",tabTo:"#5EEAD4",bodyFrom:"#B2F5EA",bodyMid:"#2DD4BF",bodyTo:"#0F766E",glow:"#2DD4BF"},
  {tabFrom:"#DCFCE7",tabTo:"#86EFAC",bodyFrom:"#BBF7D0",bodyMid:"#4ADE80",bodyTo:"#15803D",glow:"#4ADE80"},
  {tabFrom:"#FFEDD5",tabTo:"#FDBA74",bodyFrom:"#FED7AA",bodyMid:"#FB923C",bodyTo:"#C2410C",glow:"#FB923C"},
] as const;
const folderHash = (value:string) => Array.from(value).reduce((sum,char)=>sum+char.charCodeAt(0),0);
const pickFolderPalette = (label:string, index:number, usedPalettes:Set<number>) => { let paletteIndex=(folderHash(label)+index*3)%folderPalettes.length; while(usedPalettes.has(paletteIndex) && usedPalettes.size<folderPalettes.length) paletteIndex=(paletteIndex+1)%folderPalettes.length; usedPalettes.add(paletteIndex); return folderPalettes[paletteIndex]; };
const MacFinderFolder: React.FC<{label:string; index:number; frame:number; delay:number; palette:typeof folderPalettes[number]}> = ({label,index,frame,delay,palette}) => <div style={{...enter(frame,delay,0),textAlign:"center",filter:"drop-shadow(0 22px 24px rgba(0,0,0,.32))"}}><div style={{position:"relative",width:246,height:176,margin:"auto"}}><div aria-label="folder tab" style={{position:"absolute",left:18,top:0,width:96,height:36,borderRadius:"16px 18px 8px 0",background:"linear-gradient(180deg, "+palette.tabFrom+" 0%, "+palette.tabTo+" 100%)",border:"1px solid rgba(255,255,255,.64)",boxShadow:"inset 0 1px 0 rgba(255,255,255,.78), 0 8px 16px rgba(20,92,160,.18)"}}/><div style={{position:"absolute",left:0,right:0,top:22,bottom:0,borderRadius:"20px 24px 24px 24px",background:"linear-gradient(180deg, "+palette.bodyFrom+" 0%, "+palette.bodyMid+" 58%, "+palette.bodyTo+" 100%)",border:"1px solid rgba(255,255,255,.58)",boxShadow:"inset 0 1px 0 rgba(255,255,255,.78), inset 0 -18px 30px rgba(18,83,160,.28), 0 0 28px "+palette.glow+"55",overflow:"hidden"}}><div style={{position:"absolute",left:18,right:18,top:12,height:45,borderRadius:"999px",background:"linear-gradient(180deg, rgba(255,255,255,.52), rgba(255,255,255,0))"}}/><div style={{position:"absolute",left:0,right:0,bottom:0,height:34,background:"linear-gradient(180deg, transparent, rgba(13,71,138,.26))"}}/><div style={{position:"absolute",right:18,top:24,width:42,height:42,borderRadius:"50%",background:palette.glow,opacity:.3,filter:"blur(10px)"}}/></div></div><div style={{display:"inline-block",maxWidth:286,marginTop:15,padding:"6px 13px",borderRadius:10,background:"rgba(7,15,29,.52)",border:"1px solid rgba(255,255,255,.13)",backdropFilter:"blur(6px)",color:C.white,fontSize:23,lineHeight:"29px",fontWeight:900,overflowWrap:"break-word"}}>{label}</div></div>;

export const DesktopFolders: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps} = useVideoConfig(); const s=startFrame(cue,fps); const folders=listProp(cue,props,"items").slice(0,4); const usedPalettes=new Set<number>(); return <div style={{position:"absolute",left:140,top:BODY_TOP,display:"grid",gridTemplateColumns:"repeat(2, 330px)",gap:36,...enter(f,s)}}>{folders.map((folder,i)=>{ const palette=pickFolderPalette(folder,i,usedPalettes); return <MacFinderFolder key={folder+"-"+i} label={folder} index={i} frame={f} delay={s+getStaggerStartFrame(fps,i)} palette={palette}/>; })}</div>; };

export const TimeRewind: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const p=interpolate(f,[s+20,s+122],[1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const body=textProp(props,"bodyText",textProp(props,"body",textProp(props,"effectText","时间回归"))); const typed=body.slice(0,Math.min(body.length,Math.max(0,Math.floor((f-s-48)/2)))); return <div style={{position:"absolute",left:120,right:120,top:300,...enter(f,s)}}><div style={{color:C.gold,fontSize:22,fontWeight:950,letterSpacing:5}}>REWIND</div><div style={{marginTop:22,position:"relative",height:90}}><div style={{position:"absolute",left:0,right:0,top:37,height:5,background:"rgba(255,255,255,.2)"}}/><div style={{position:"absolute",left:`${p*100}%`,top:22,width:34,height:34,borderRadius:"50%",background:C.gold,transform:"translateX(-50%)",boxShadow:"0 0 20px rgba(255,209,102,.9)"}}/>{listProp(cue,props,"years").slice(0,5).map((year,i,years)=><div key={year+"-"+i} style={{position:"absolute",left:`${years.length===1?0:i*(100/(years.length-1))}%`,top:52,color:C.white,fontSize:22,fontWeight:950,transform:"translateX(-50%)"}}>{year}</div>)}</div><div style={{marginTop:36,color:C.white,fontSize:65,fontWeight:950}}>{typed}<span style={{color:C.gold}}>{typed.length<body.length?"|":""}</span></div></div>; };

export const ClipboardNote: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=startFrame(cue,fps); const body=textProp(props,"body",textProp(props,"bodyText",textProp(props,"effectText",cue.caption.zh))); const subText=textProp(props,"highlightQuote",textProp(props,"subText","")); const label=textProp(props,"label","DECISION NOTE"); return <Panel color={C.gold} style={{position:"absolute",left:175,top:BODY_TOP,width:760,minHeight:560,padding:"48px 54px",background:"rgba(28,25,15,.88)",...enter(f,s)}}><div style={{position:"absolute",left:270,top:-22,width:260,height:44,borderRadius:7,background:"#B6BDC6"}}/><div style={{color:C.gold,fontSize:18,fontWeight:950,letterSpacing:4}}>{label}</div><div style={{marginTop:28,color:C.white,fontSize:48,lineHeight:"62px",fontWeight:950,overflowWrap:"break-word"}}>{body}</div>{subText?<div style={{marginTop:22,color:C.dim,fontSize:26,lineHeight:"38px",fontWeight:800,overflowWrap:"break-word"}}>{subText}</div>:null}<div style={{marginTop:34,borderTop:"2px solid rgba(255,209,102,.55)",width:interpolate(f,[s+50,s+110],[0,560],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}}/></Panel>; };

export const ClosingChecklist: React.FC<LayoutEffectProps> = ({cue, props}) => {
  const f = useCurrentFrame();
  const {fps} = useVideoConfig();
  const s = startFrame(cue, fps);
  const boxColor = boxColorProp(props);
  const items = listProp(cue, props, "items").slice(0, 4);
  return <div style={{position: "absolute", left: 120, top: BODY_TOP, width: 760, ...enter(f, s)}}>
    <div style={{color: C.white, fontSize: 56, lineHeight: "66px", fontWeight: 950}}>{textProp(props, "title", cue.section.subtitle)}</div>
    <div style={{marginTop: 26, display: "flex", flexDirection: "column", gap: 14}}>{items.map((row, i) => <Panel key={row+"-"+i} color={boxColor} style={{padding: "16px 20px", display: "flex", alignItems: "center", gap: 16, ...enter(f, s + getStaggerStartFrame(fps, i))}}><Mark value="✓" color={boxColor}/><div style={{color: C.white, fontSize: 31, fontWeight: 950}}>{row}</div></Panel>)}</div>
  </div>;
};




