import type {JasonWuTranscriptCue} from "./timeline";

export const jasonWuLongTranscript: JasonWuTranscriptCue[] = [
  {
    start: 0.1,
    end: 10.006,
    zh: "执掌苹果整整 15 年的蒂姆库克正式交棒，50 岁的前硬件工程高级副总裁约翰特纳斯，正式成为这家科技巨擘的第七任掌门人。",
    en: "Cook hands Apple to John Ternus after fifteen years.",
  },
  {
    start: 9.956,
    end: 22.141,
    zh: "回看库克的 15 年成绩单：苹果市值从 2011 年接棒时的 3500 亿美元，一举跨过 4.6 万亿美元峰值，复合年增长率高达 18.7%，膨胀超过 13 倍。",
    en: "Apple rises from $350B to $4.6T with 18.7% CAGR.",
  },
  {
    start: 22.141,
    end: 27.347,
    zh: "全球年营收从 1080 亿美元跃升至破纪录的 4160 亿美元。",
    en: "Revenue jumps from $108B to a record $416B.",
  },
  {
    start: 27.347,
    end: 39.706,
    zh: "但这艘巨轮已然行至浅滩：近 8 个季度，大中华区 iPhone 出货量同比承压下跌 6.5%，全球智能手机市占率在 18.2% 至 20.1% 窄幅震荡。",
    en: "China iPhone shipments and global share enter pressure.",
  },
  {
    start: 39.706,
    end: 48.75,
    zh: "资本市场在欢呼万亿现金储备的同时，所有人都在等待：这台被冠以微操大师称号的机器，如何打破增长天花板？",
    en: "Markets now wait for a new growth ceiling breaker.",
  },
  {
    start: 48.75,
    end: 54.413,
    zh: "过去 15 年，库克用精算师式的冷静，重新定义了消费电子的生产逻辑。",
    en: "Cook redefined production with actuarial calm.",
  },
  {
    start: 54.413,
    end: 63.26,
    zh: "他将苹果供应链的库存周转天数，从行业平均的 30 天极限压缩到惊人的 2 到 5 天，实现真正的零库存运转。",
    en: "Inventory days collapse from 30 to 2-5.",
  },
  {
    start: 63.26,
    end: 72.489,
    zh: "更可怕的是利润榨取能力：iPhone 以全球 20% 的出货量份额，卷走了整个智能手机市场超过 85% 的营业利润。",
    en: "20% shipment share captures over 85% of profits.",
  },
  {
    start: 72.489,
    end: 82.934,
    zh: "与此同时，毛利率高达 74% 的服务生态异军突起，iCloud、Apple Music 与 App Store 年入千亿美元，占总营收比重突破 25%。",
    en: "Services reach $100B and exceed 25% of revenue.",
  },
  {
    start: 82.934,
    end: 86.836,
    zh: "然而，精准刀法的代价是创新的全面保守。",
    en: "The cost of precision is innovation conservatism.",
  },
  {
    start: 86.836,
    end: 99.097,
    zh: "为了守住 45% 的整机综合毛利率，高风险的前沿形态屡屡为良品率让步，研发试错被严密的财务模型扼杀，挤牙膏成了这具完美商业机器挥之不去的阴影。",
    en: "Margins protect the machine while risky bets are cut.",
  },
  {
    start: 99.097,
    end: 104.717,
    zh: "约翰特纳斯的接棒，宣告了苹果由运营至上向工程师独裁的强势回归。",
    en: "Ternus signals the return of engineering power.",
  },
  {
    start: 104.717,
    end: 114.695,
    zh: "这位在苹果浸润 25 年的纯血工程师，曾亲自主导了初代 iPad、AirPods 降噪声学架构、以及搭载 M 系列芯片的 MacBook Pro 硬件重塑。",
    en: "He shaped iPad, AirPods, and M-series MacBook Pro.",
  },
  {
    start: 114.695,
    end: 125.902,
    zh: "他最著名的战役，就是在乔纳森伊夫追求病态纤薄而砍掉接口后，力排众议将 MagSafe、HDMI 与 SD 卡槽重新带回 Mac，挽救了专业工作者市场。",
    en: "He brought MagSafe, HDMI, and SD back to Mac.",
  },
  {
    start: 125.902,
    end: 138.695,
    zh: "数据说明了一切：在特纳斯主导 Apple Silicon 整合之后，Mac 产线每瓦性能比飙升 300%，续航时间直接突破 22 小时大关，推动 Mac 业务在 PC 寒冬中逆势增长 14%。",
    en: "Apple Silicon pushes efficiency 300% and battery past 22h.",
  },
  {
    start: 138.695,
    end: 147.336,
    zh: "相比库克在财报电话会上的数字拆解，特纳斯更痴迷于 0.01 毫米的加工公差、均热板散热架构与微米级封装。",
    en: "Ternus obsesses over 0.01mm tolerances and thermal design.",
  },
  {
    start: 147.336,
    end: 152.239,
    zh: "工程师的回归，意味着产品定义权重新夺回了最高裁决权。",
    en: "Engineering retakes the highest product authority.",
  },
  {
    start: 152.239,
    end: 157.967,
    zh: "特纳斯面临的战场远比想象严苛，他必须在三大核心阵地上发起逆袭：",
    en: "Ternus must counterattack on three core fronts.",
  },
  {
    start: 157.967,
    end: 160.673,
    zh: "第一，研发预算的结构性释放。",
    en: "First: release the R&D budget toward 10%.",
  },
  {
    start: 160.673,
    end: 176.795,
    zh: "苹果的研发支出占营收比重长期维持在 7.5% 至 8% 之间，年研发投入约 310 亿美元；在特纳斯治下，这一占比有望破天荒冲击 10%，为折叠屏与新形态硬件的良率攻关扫清财务阻碍。",
    en: "Higher R&D clears the path for foldable hardware.",
  },
  {
    start: 176.795,
    end: 179.328,
    zh: "第二，端侧 AI 算力护城河。",
    en: "Second: build the on-device AI moat.",
  },
  {
    start: 179.328,
    end: 187.991,
    zh: "面对生成式模型的狂轰滥炸，特纳斯握有全球最恐怖的底牌：22 亿台活跃 Apple 设备的端侧 NPU 互联网络。",
    en: "2.2B Apple devices form the NPU network.",
  },
  {
    start: 187.991,
    end: 196.426,
    zh: "新一代 M5 与 A19 Pro 芯片的晶体管密度和神经处理单元算力，将把端侧大模型的吞吐延迟压低到 15 毫秒以内。",
    en: "M5 and A19 Pro push latency below 15ms.",
  },
  {
    start: 196.426,
    end: 198.828,
    zh: "第三，供应链重心平衡。",
    en: "Third: rebalance the supply chain.",
  },
  {
    start: 198.828,
    end: 210.35,
    zh: "面对全球供应链重组，特纳斯需要在维持 98% 顶级品控的前提下，将 25% 的产能分散至东南亚与印度，这是一场精度与规模的双重钢丝绳。",
    en: "25% capacity shifts while 98% quality must hold.",
  },
  {
    start: 210.35,
    end: 218.023,
    zh: "蒂姆库克留下的是一艘拥有 1600 亿美元净现金流、抗风险能力堪比主权基金的商业航空母舰；",
    en: "Cook leaves $160B in net cash flow.",
  },
  {
    start: 218.023,
    end: 226.284,
    zh: "而约翰特纳斯的历史使命，则是为这艘满载货物的巨舰，重新点燃那个属于极客、属于颠覆式创新的核反应堆。",
    en: "Ternus must reignite the reactor of geek innovation.",
  },
  {
    start: 226.284,
    end: 234.219,
    zh: "告别了精密计算的财会时代，由纯血工程师掌舵的全新苹果，能否再次拿出让世界窒息的 One more thing？",
    en: "Can the new Apple deliver One more thing?",
  },
  {
    start: 234.219,
    end: 238.85,
    zh: "在评论区打出你的预测：你看好特纳斯开启的新时代吗？",
    en: "Leave your prediction in the comments.",
  },
];
