import React from "react";
import {Easing, interpolate, spring, useCurrentFrame, useVideoConfig} from "remotion";
import type {LayoutEffectProps} from "./DemoEffectComponents";
import {resolveContentItems, resolveContentText} from "./layoutRuntime";

export const RECOVERED_LAYOUT_KEYS = ["platform-shift-line", "tradeoff-reject-round", "recovery-progress-bars", "hud-glow-stack", "briefing-poster", "rewind-milestones", "flying-paper-stack", "checklist-editorial"] as const;

const BLUE = "var(--primary-accent)";
const GOLD = "#FFD166";
const GREEN = "#38D7A6";
const RED = "#FF6170";
const WHITE = "#FFFFFF";
const DIM = "rgba(255,255,255,.62)";
const ease = Easing.bezier(.16, 1, .3, 1);
const clean = (value: unknown) => typeof value === "string" && value.trim() ? value.trim() : "";
const text = (cue: LayoutEffectProps["cue"], props: Record<string, unknown> | undefined, key: string, fallback?: string) => clean(props?.[key]) || fallback || resolveContentText(cue, props, "headline");
const items = (cue: LayoutEffectProps["cue"], props: Record<string, unknown> | undefined, keys = ["items"]) => resolveContentItems(cue, props, keys).slice(0, 4);
const start = (cue: LayoutEffectProps["cue"], fps: number) => Math.round(cue.start * fps);
const enter = (frame: number, at: number, x = -44, y = 20, frames = 24) => ({opacity: interpolate(frame, [at, at + frames], [0, 1], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease}), transform: "translate(" + interpolate(frame, [at, at + frames], [x, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease}) + "px," + interpolate(frame, [at, at + frames], [y, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease}) + "px)"});
const header = (cue: LayoutEffectProps["cue"], props: Record<string, unknown> | undefined) => props?.__externalSectionLabel ? null : <div style={{position:"absolute",left:76,top:58,zIndex:3}}><div style={{color:BLUE,fontSize:30,fontWeight:950,letterSpacing:8,textShadow:"0 0 20px rgba(0,132,255,.55)"}}>{text(cue,props,"eyebrow",cue.section.eyebrow).toUpperCase()}</div><div style={{marginTop:8,color:WHITE,fontSize:25,fontWeight:950}}>{text(cue,props,"headline",cue.section.subtitle)}</div></div>;
const CircleMark: React.FC<{color:string; value:string}> = ({color,value}) => <span style={{width:52,height:52,borderRadius:"50%",border:"3px solid "+color,color,display:"inline-flex",alignItems:"center",justifyContent:"center",fontSize:34,fontWeight:950,boxShadow:"0 0 18px "+color+"66"}}>{value}</span>;

export const PlatformShiftLine: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const count=Number(props?.count ?? props?.metricValue ?? 3) || 0; const value=Math.round(interpolate(f,[s+20,s+88],[0,count],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease})); const dots=items(cue,props,["milestones","items"]); const line=interpolate(f,[s+34,s+110],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:74,top:238,...enter(f,s)}}><div style={{display:"flex",alignItems:"center",gap:24}}><div style={{fontSize:136,color:WHITE,fontWeight:950,lineHeight:1}}>●</div><div style={{fontSize:136,color:WHITE,fontWeight:950,lineHeight:1}}>{value}</div><div style={{color:BLUE,fontSize:38,fontWeight:950,letterSpacing:5}}>{text(cue,props,"metricLabel","产品线")}</div></div><div style={{marginTop:150,color:DIM,fontSize:30,fontWeight:900}}>{text(cue,props,"summary",cue.caption.zh)} <span style={{color:BLUE,fontSize:68}}>{value}</span></div><div style={{position:"relative",marginTop:58,width:1000,height:92}}><div style={{position:"absolute",top:25,left:0,width:1000,height:5,background:"rgba(255,255,255,.5)"}}/><div style={{position:"absolute",top:25,left:0,width:1000*line,height:5,background:BLUE,boxShadow:"0 0 18px rgba(0,132,255,.8)"}}/>{Array.from({length:Math.max(4,dots.length+2)}).map((_,i)=><i key={i} style={{position:"absolute",top:i===Math.max(4,dots.length+2)-1?7:16,left:(i/(Math.max(3,dots.length+1)))*960,width:i===Math.max(4,dots.length+2)-1?40:19,height:i===Math.max(4,dots.length+2)-1?40:19,borderRadius:"50%",background:i===Math.max(4,dots.length+2)-1?BLUE:WHITE,boxShadow:i===Math.max(4,dots.length+2)-1?"0 0 24px "+BLUE:"none"}}/>)}<b style={{position:"absolute",left:0,top:73,color:GOLD,fontSize:25,letterSpacing:3}}>{text(cue,props,"startLabel","起点")}</b><b style={{position:"absolute",right:0,top:73,color:BLUE,fontSize:25,letterSpacing:3}}>{text(cue,props,"endLabel","目标阶段")}</b></div></div></div>; };

export const TradeoffRejectRound: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const rows=items(cue,props); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:96,top:275,...enter(f,s)}}><div style={{color:RED,fontSize:24,fontWeight:950,letterSpacing:6}}>{text(cue,props,"label","WHAT WENT WRONG")}</div><div style={{marginTop:28,color:WHITE,fontSize:58,fontWeight:950}}>{text(cue,props,"title",cue.section.subtitle)}</div><div style={{display:"grid",gap:30,marginTop:42}}>{rows.map((row,i)=><div key={row+i} style={{display:"flex",alignItems:"center",gap:22,...enter(f,s+15+i*16,-30,0)}}><CircleMark color={RED} value="×"/><span style={{color:WHITE,fontSize:40,fontWeight:950}}>{row}</span></div>)}</div></div></div>; };

export const RecoveryProgressBars: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const rows=items(cue,props); const values=Array.isArray(props?.values)?props.values:[]; return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:100,top:278,width:1130,...enter(f,s)}}><div style={{color:GREEN,fontSize:24,fontWeight:950,letterSpacing:6}}>{text(cue,props,"label","RECOVERY TRACK")}</div><div style={{marginTop:24,color:WHITE,fontSize:58,fontWeight:950}}>{text(cue,props,"title",cue.section.subtitle)}</div><div style={{display:"grid",gap:31,marginTop:42}}>{rows.map((row,i)=>{const target=Number(values[i] ?? [68,54,42][i] ?? 60);const progress=interpolate(f,[s+30+i*16,s+96+i*16],[0,target],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease});return <div key={row+i} style={{...enter(f,s+14+i*16,0,14)}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:34,fontWeight:950,color:WHITE}}>{row}</span><span style={{fontSize:44,color:GREEN,fontWeight:950}}>✓</span></div><div style={{height:18,marginTop:13,borderRadius:20,background:"rgba(255,255,255,.2)",overflow:"hidden"}}><div style={{height:"100%",width:progress+"%",background:i===1?GOLD:GREEN,boxShadow:"0 0 18px "+(i===1?GOLD:GREEN)}}/></div></div>})}</div></div></div>; };

export const HudGlowStack: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const rows=items(cue,props,["items","steps"]); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:84,top:248,width:1040,display:"grid",gap:20}}>{rows.map((row,i)=>{const p=spring({frame:f-s-14-i*17,fps,config:{damping:14,stiffness:150}});const accent=i===1?GOLD:BLUE;const shine=interpolate(f,[s+25+i*17,s+55+i*17],[-170,1120],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.linear});return <div key={row+i} style={{height:122,padding:"22px 28px",display:"flex",alignItems:"center",justifyContent:"space-between",border:"2px solid "+(i===1?GOLD:BLUE),borderRadius:18,overflow:"hidden",background:"rgba(3,9,18,.9)",boxShadow:"0 0 28px "+(i===1?GOLD:BLUE)+"44",opacity:Math.min(1,p),transform:"translateX("+interpolate(p,[0,1],[-80,0])+"px)"}}><div style={{position:"absolute",left:shine,top:-32,width:118,height:190,transform:"rotate(18deg)",pointerEvents:"none",background:"linear-gradient(90deg, transparent, "+accent+"66, rgba(255,255,255,.62), transparent)",mixBlendMode:"screen"}}/><div style={{display:"flex",alignItems:"center",gap:20}}><b style={{width:52,height:52,borderRadius:"50%",background:i===1?GOLD:BLUE,color:"#06111c",display:"grid",placeItems:"center",fontSize:21}}>{(i + 1 < 10 ? "0" : "") + String(i + 1)}</b><div><div style={{fontSize:37,fontWeight:950,color:WHITE}}>{row}</div><div style={{marginTop:5,color:i===1?GOLD:BLUE,fontSize:18,fontWeight:900,letterSpacing:4}}>{text(cue,props,"subLabel",cue.section.eyebrow)}</div></div></div><CircleMark color={i===1?GOLD:BLUE} value=""/></div>})}</div></div>; };

export const BriefingPoster: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const rows=items(cue,props); const tilt=interpolate(f,[s,s+32],[-3,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const entrance=enter(f,s,-70,20,32); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:170,top:205,width:1060,minHeight:550,padding:"90px 82px",background:"#F4EEDB",color:"#101826",boxShadow:"0 24px 48px rgba(0,0,0,.48)",opacity:entrance.opacity,transform:entrance.transform+" rotate("+tilt+"deg)"}}><div style={{position:"absolute",left:430,top:-28,width:250,height:62,borderRadius:10,background:"#667689"}}/><div style={{fontSize:22,fontWeight:950,letterSpacing:7}}>{text(cue,props,"label","PRODUCT NOTE")}</div><div style={{marginTop:34,fontSize:64,lineHeight:"78px",fontWeight:950}}>{text(cue,props,"title",cue.section.subtitle)}</div><div style={{display:"grid",gap:25,marginTop:35}}>{rows.map((row,i)=><div key={row+i} style={{display:"flex",gap:18,alignItems:"center",fontSize:35,fontWeight:900,...enter(f,s+18+i*15,-20,0)}}><span style={{color:"#149D68",fontSize:38}}>☑</span>{row}</div>)}</div></div></div>; };

export const RewindMilestones: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const years=items(cue,props,["years","items"]).slice(0,3); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:100,top:238,right:100}}><div style={{color:GOLD,fontSize:24,fontWeight:950,letterSpacing:6}}>{text(cue,props,"label","TIME REWIND")}</div><div style={{position:"relative",height:320,marginTop:30}}><div style={{position:"absolute",top:72,left:0,right:0,height:4,background:"rgba(255,255,255,.72)"}}/>{years.map((year,i)=>{const x=(i/(Math.max(1,years.length-1)))*100;const p=spring({frame:f-s-16-i*18,fps,config:{damping:14,stiffness:160}});return <div key={year+i} style={{position:"absolute",left:x+"%",top:0,transform:"translateX(-50%) scale("+interpolate(p,[0,1],[.74,1])+")",opacity:Math.min(1,p),textAlign:"center"}}><i style={{display:"block",width:38,height:38,margin:"0 auto 52px",borderRadius:"50%",background:i===years.length-1?GOLD:BLUE,boxShadow:"0 0 20px "+(i===years.length-1?GOLD:BLUE)}}/><b style={{display:"block",fontSize:78,color:WHITE,lineHeight:1}}>{year}</b><span style={{display:"block",marginTop:22,fontSize:22,color:DIM,fontWeight:900,letterSpacing:2}}>{text(cue,props,"milestoneLabel","CAPABILITY")}</span></div>})}<b style={{position:"absolute",right:80,top:218,color:GOLD,fontSize:28}}>&lt;&lt; REWIND</b></div><div style={{marginTop:14,fontSize:66,color:WHITE,fontWeight:950}}>{text(cue,props,"title",cue.section.subtitle)}</div></div></div>; };

export const FlyingPaperStack: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const cards: Array<[number, number, string]>=[[-90,-45,BLUE],[0,0,BLUE],[90,45,RED]]; return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:190,top:238,width:1050,height:470}}>{cards.map(([x,y,color],i)=>{const p=spring({frame:f-s-10-i*10,fps,config:{damping:15,stiffness:150}});return <div key={i} style={{position:"absolute",inset:0,padding:"58px 70px",background:"#F6F0E2",color:"#101826",borderTop:"14px solid "+color,boxShadow:"0 18px 42px rgba(0,0,0,.36)",opacity:Math.min(1,p),transform:"translate("+interpolate(p,[0,1],[x*2,x])+"px,"+interpolate(p,[0,1],[y*2,y])+"px) rotate("+(i-1)*2+"deg)"}}><div style={{fontSize:20,fontWeight:950,letterSpacing:6}}>THE PRODUCT PAPER</div><div style={{marginTop:36,fontSize:56,fontWeight:950}}>{i===2?text(cue,props,"headline",cue.section.subtitle):text(cue,props,"ghostTitle",cue.section.subtitle)}</div><div style={{marginTop:24,borderTop:"2px solid #7E8794"}}/><div style={{marginTop:20,fontSize:29,fontWeight:850}}>{text(cue,props,"body",cue.caption.zh)}</div></div>})}</div></div>; };

export const ChecklistEditorial: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const rows=items(cue,props); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:105,top:245,width:860,...enter(f,s)}}><div style={{color:GOLD,fontSize:24,fontWeight:950,letterSpacing:6}}>{text(cue,props,"label",cue.section.eyebrow)}</div><div style={{marginTop:28,color:WHITE,fontSize:72,lineHeight:"86px",fontWeight:950}}>{text(cue,props,"title",cue.section.subtitle)}</div><div style={{display:"grid",gap:24,marginTop:38}}>{rows.map((row,i)=><div key={row+i} style={{display:"flex",alignItems:"center",gap:20,...enter(f,s+18+i*17,-24,0)}}><span style={{width:54,height:54,border:"3px solid "+BLUE,color:BLUE,fontSize:40,lineHeight:"48px",textAlign:"center"}}>✓</span><b style={{fontSize:42,color:WHITE}}>{row}</b></div>)}</div></div></div>; };
