import React from "react";
import {Easing, interpolate, spring, useCurrentFrame, useVideoConfig} from "remotion";
import type {LayoutEffectProps} from "./DemoEffectComponents";
import {resolveContentItems, resolveContentText} from "./layoutRuntime";
import {IcoFontPathIcon} from "./components/common/IcoFontPathIcon";
import {readTextSlot} from "./components/common/EditableTextSlots";

export const RECOVERED_LAYOUT_KEYS = ["platform-shift-line", "tradeoff-reject-round", "recovery-progress-bars", "hud-glow-stack", "briefing-poster", "rewind-milestones", "flying-paper-stack", "checklist-editorial"] as const;

const BLUE = "#0A84FF";
const GOLD = "#FFD166";
const GREEN = "#38D7A6";
const RED = "#FF5B5B";
const WHITE = "#FFFFFF";
const DIM = "rgba(255,255,255,.62)";
const ease = Easing.bezier(.16, 1, .3, 1);
const BODY_TOP = 300;
const clean = (value: unknown) => typeof value === "string" ? value.trim() : "";
const strings = (value: unknown) => Array.isArray(value) ? value.map(clean).filter(Boolean) : [];
const optionalStrings = (value: unknown) => Array.isArray(value) ? value.map((item) => typeof item === "string" ? item.trim() : "") : [];
const text = (cue: LayoutEffectProps["cue"], props: Record<string, unknown> | undefined, key: string, fallback?: string) => typeof props?.[key] === "string" ? clean(props[key]) : fallback ?? resolveContentText(cue, props, "headline");
const itemLimit = (props: Record<string, unknown> | undefined, fallback = 4) => Math.max(1, Math.min(8, Math.round(Number((props?.designTokens as Record<string, unknown> | undefined)?.defaultItemCount) || fallback)));
const items = (cue: LayoutEffectProps["cue"], props: Record<string, unknown> | undefined, keys = ["items"], maxItems = 4) => { const rows = resolveContentItems(cue, props, keys); return rows.slice(0, Math.min(8, Math.max(itemLimit(props, maxItems), rows.length))); };
const start = (cue: LayoutEffectProps["cue"], fps: number) => Math.round(cue.start * fps);
const tokenNumber = (props: Record<string, unknown> | undefined, key: string, fallback: number) => { const value = (props?.designTokens as Record<string, unknown> | undefined)?.[key] ?? props?.[key]; const next = Number(value); return Number.isFinite(next) ? Math.max(.6, Math.min(1.2, next)) : fallback; };
const enter = (frame: number, at: number, x = -44, y = 20, frames = 24) => ({opacity: interpolate(frame, [at, at + frames], [0, 1], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease}), transform: "translate(" + interpolate(frame, [at, at + frames], [x, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease}) + "px," + interpolate(frame, [at, at + frames], [y, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease}) + "px)"});
const header = (cue: LayoutEffectProps["cue"], props: Record<string, unknown> | undefined) => { const headerScale = tokenNumber(props,"headerScale",1); return props?.__externalSectionLabel ? null : <div style={{position:"absolute",left:76,top:58,zIndex:3,transform:"scale("+headerScale+")",transformOrigin:"top left"}}><div style={{color:BLUE,fontSize:30,fontWeight:950,letterSpacing:8,textShadow:"0 0 20px rgba(0,132,255,.55)"}}>{text(cue,props,"eyebrow",cue.section.eyebrow).toUpperCase()}</div><div style={{marginTop:8,color:WHITE,fontSize:25,fontWeight:950}}>{text(cue,props,"headline",cue.section.subtitle)}</div></div>; };
const CircleMark: React.FC<{color:string; value:string}> = ({color,value}) => <span style={{width:52,height:52,flex:"0 0 auto",borderRadius:"50%",border:"3px solid "+color,color,display:"inline-flex",alignItems:"center",justifyContent:"center",fontSize:34,fontWeight:950,boxShadow:"0 0 18px "+color+"66"}}>{value}</span>;

export const PlatformShiftLine: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const count=Number(props?.count ?? props?.metricValue ?? 3) || 0; const value=Math.round(interpolate(f,[s+20,s+88],[0,count],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease})); const dots=items(cue,props,["milestones","items"]); const line=interpolate(f,[s+34,s+110],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:74,top:BODY_TOP,...enter(f,s)}}><div style={{display:"flex",alignItems:"center",gap:24}}><div style={{fontSize:136,color:WHITE,fontWeight:950,lineHeight:1}}>{value}</div><div style={{color:BLUE,fontSize:38,fontWeight:950,letterSpacing:5}}>{text(cue,props,"metricLabel","产品线")}</div></div><div style={{marginTop:150,color:BLUE,fontSize:35,fontWeight:900}}>{text(cue,props,"summary",cue.caption.zh)}</div><div style={{position:"relative",marginTop:58,width:1000,height:92}}><div style={{position:"absolute",top:25,left:0,width:1000,height:5,background:"rgba(255,255,255,.5)"}}/><div style={{position:"absolute",top:25,left:0,width:1000*line,height:5,background:BLUE,boxShadow:"0 0 18px rgba(0,132,255,.8)"}}/>{Array.from({length:Math.max(4,dots.length+2)}).map((_,i)=><i key={i} style={{position:"absolute",top:i===Math.max(4,dots.length+2)-1?7:16,left:(i/(Math.max(3,dots.length+1)))*960,width:i===Math.max(4,dots.length+2)-1?40:19,height:i===Math.max(4,dots.length+2)-1?40:19,borderRadius:"50%",background:i===Math.max(4,dots.length+2)-1?BLUE:WHITE,boxShadow:i===Math.max(4,dots.length+2)-1?"0 0 24px "+BLUE:"none"}}/>)}<b style={{position:"absolute",left:0,top:73,color:GOLD,fontSize:25,letterSpacing:3}}>{text(cue,props,"startLabel","起点")}</b><b style={{position:"absolute",right:0,top:73,color:BLUE,fontSize:25,letterSpacing:3}}>{text(cue,props,"endLabel","目标阶段")}</b></div></div></div>; };

export const TradeoffRejectRound: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const rows=items(cue,props,["items","steps"],3); const body=text(cue,props,"bodyText",text(cue,props,"body",text(cue,props,"effectText",cue.section.subtitle))); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:96,top:BODY_TOP,...enter(f,s)}}><div style={{color:RED,fontSize:24,fontWeight:950,letterSpacing:6}}>{text(cue,props,"label","风险排除")}</div><div style={{marginTop:28,color:WHITE,fontSize:58,lineHeight:"68px",fontWeight:950,maxWidth:960,overflowWrap:"break-word"}}>{body}</div><div style={{display:"grid",gap:30,marginTop:42}}>{rows.map((row,i)=><div key={row+i} style={{display:"flex",alignItems:"center",gap:22,...enter(f,s+15+i*16,-30,0)}}><CircleMark color={RED} value="×"/><span style={{color:WHITE,fontSize:40,fontWeight:950}}>{row}</span></div>)}</div></div></div>; };

const progressOffsets = [-12, 8, -4, 14, -9, 5, 0, 11];
export const RecoveryProgressBars: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const rows=items(cue,props); const subtitles=strings(props?.itemSubtitles ?? props?.subLabels); const globalProgress=Number(props?.progress ?? props?.value); const baseProgress=Number.isFinite(globalProgress)?globalProgress:68; const body=text(cue,props,"bodyText",text(cue,props,"body",text(cue,props,"effectText",cue.section.subtitle))); const contentScale=tokenNumber(props,"contentScale",.66); const entrance=enter(f,s); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:100,top:BODY_TOP,width:1130,opacity:entrance.opacity,transform:entrance.transform+" scale("+contentScale+")",transformOrigin:"top left"}}><div style={{color:GREEN,fontSize:24,fontWeight:950,letterSpacing:6}}>{text(cue,props,"label",text(cue,props,"category","RECOVERY TRACK"))}</div><div style={{marginTop:24,color:WHITE,fontSize:58,fontWeight:950}}>{body}</div><div style={{display:"grid",gap:31,marginTop:42}}>{rows.map((row,i)=>{const target=Math.max(0,Math.min(100,baseProgress+progressOffsets[i%progressOffsets.length]));const progress=interpolate(f,[s+30+i*16,s+96+i*16],[0,target],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease});return <div key={row+i} style={{...enter(f,s+14+i*16,0,14)}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:18}}><div><span style={{fontSize:34,fontWeight:950,color:WHITE}}>{row}</span>{subtitles[i]?<span style={{display:"block",marginTop:4,fontSize:16,color:DIM,fontWeight:850,letterSpacing:2}}>{subtitles[i]}</span>:null}</div><span style={{fontSize:34,color:GREEN,fontWeight:950}}>{Math.round(target)}%</span></div><div style={{height:18,marginTop:13,borderRadius:20,background:"rgba(255,255,255,.2)",overflow:"hidden"}}><div style={{height:"100%",width:progress+"%",background:i===1?GOLD:GREEN,boxShadow:"0 0 18px "+(i===1?GOLD:GREEN)}}/></div></div>})}</div></div></div>; };

export const HudGlowStack: React.FC<LayoutEffectProps> = ({cue, props}) => {
  const f = useCurrentFrame();
  const {fps} = useVideoConfig();
  const s = start(cue, fps) + 12;
  const rows = items(cue, props, ["items", "steps"]);
  const subtitleSource = Array.isArray(props?.itemSubtitles) ? props?.itemSubtitles : Array.isArray(props?.subLabels) ? props?.subLabels : undefined;
  const subtitles = optionalStrings(subtitleSource);
  const hasExplicitSubtitles = Array.isArray(subtitleSource);
  const isEnglish = cue.language === "en";
  const stackWidth = isEnglish ? 1070 : 693;
  const defaultPayload = {subLabel: cue.section.eyebrow};
  const usedIconNames = new Set<string>();

  return <div style={{position: "absolute", inset: 0}}>{header(cue, props)}<div style={{position: "absolute", left: 84, top: BODY_TOP, width: stackWidth, display: "grid", gap: isEnglish ? 18 : 20}}>{rows.map((row, i) => {
    const p = spring({frame: f - s - 14 - i * 17, fps, config: {damping: 14, stiffness: 150}});
    const hudPalette = [BLUE, GOLD, GREEN, "#B26BFF"];
    const accent = hudPalette[i % hudPalette.length];
    const shine = interpolate(f, [s + 25 + i * 17, s + 55 + i * 17], [-170, stackWidth + 68], {extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.linear});
    const title = readTextSlot({title: row}, "title", undefined, "");
    const subtitle = hasExplicitSubtitles ? (subtitles[i] ?? "") : readTextSlot(props, "subLabel", defaultPayload, cue.section.eyebrow);
    return <div key={row + i} style={{minHeight: isEnglish ? 136 : 122, height: isEnglish ? undefined : 122, padding: isEnglish ? "22px 30px" : "22px 28px", display: "flex", alignItems: "center", gap: 22, border: "2px solid " + accent, borderRadius: 18, overflow: "hidden", background: "rgba(3,9,18,.9)", boxShadow: "0 0 28px " + accent + "44", opacity: Math.min(1, p), transform: "translateX(" + interpolate(p, [0, 1], [-80, 0]) + "px)"}}>
      <div style={{position: "absolute", left: shine, top: -32, width: 118, height: 190, transform: "rotate(18deg)", pointerEvents: "none", background: "linear-gradient(90deg, transparent, " + accent + "66, rgba(255,255,255,.62), transparent)", mixBlendMode: "screen"}} />
      <div style={{display: "flex", alignItems: "center", gap: 20, minWidth: 0, flex: 1}}>
        <b style={{width: 52, height: 52, flex: "0 0 auto", marginRight: 2, borderRadius: "50%", background: "rgba(255,255,255,.08)", border: "2px solid " + accent, color: "#06111c", display: "grid", placeItems: "center", fontSize: 21, boxShadow: "0 0 18px " + accent + "77"}}><IcoFontPathIcon seed={title + i} color={accent} size={29} usedNames={usedIconNames} fallbackIndex={i} /></b>
        <div style={{minWidth: 0, flex: 1}}><div style={{fontSize: isEnglish ? 36 : 37, lineHeight: isEnglish ? "44px" : undefined, fontWeight: 950, color: WHITE, display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden", overflowWrap: "normal", wordBreak: "normal", hyphens: "auto"}}>{title}</div>{subtitle ? <div style={{marginTop: 5, color: accent, fontSize: 18, fontWeight: 900, letterSpacing: isEnglish ? 2 : 4, display: "-webkit-box", WebkitLineClamp: 1, WebkitBoxOrient: "vertical", overflow: "hidden", overflowWrap: "normal", wordBreak: "normal", hyphens: "auto"}}>{subtitle}</div> : null}</div>
      </div>
      <CircleMark color={accent} value="" />
    </div>;
  })}</div></div>;
};
export const BriefingPoster: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const rows=items(cue,props,["items","steps"],4); const isSingleItem=rows.length===1; const body=text(cue,props,"body",text(cue,props,"bodyText",text(cue,props,"effectText",cue.caption.zh || cue.section.subtitle))); const tilt=interpolate(f,[s,s+32],[-3,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease}); const entrance=enter(f,s,-70,20,32); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:170,top:335,width:1060,minHeight:550,padding:"90px 82px",background:"#F4EEDB",color:"#101826",boxShadow:"0 24px 48px rgba(0,0,0,.48)",opacity:entrance.opacity,transform:entrance.transform+" rotate("+tilt+"deg)"}}><div style={{position:"absolute",left:430,top:-28,width:250,height:62,borderRadius:10,background:"#667689"}}/><div style={{fontSize:22,fontWeight:950,letterSpacing:7}}>{text(cue,props,"label","PRODUCT NOTE")}</div><div style={{marginTop:34,fontSize:64,lineHeight:"78px",fontWeight:950,overflowWrap:"break-word"}}>{body}</div><div style={{display:"grid",gap:isSingleItem?0:25,marginTop:isSingleItem?52:35,minHeight:isSingleItem?180:undefined,alignContent:isSingleItem?"center":undefined}}>{rows.map((row,i)=><div key={row+i} style={{display:"flex",gap:18,alignItems:"center",minHeight:isSingleItem?120:undefined,justifyContent:isSingleItem?"center":"flex-start",fontSize:isSingleItem?42:35,fontWeight:900,...enter(f,s+18+i*15,-20,0)}}><span style={{color:"#149D68",fontSize:38}}>☑</span><span style={{minWidth:0,overflowWrap:"break-word",wordBreak:"keep-all",lineHeight:1.28}}>{row}</span></div>)}</div></div></div>; };

export const RewindMilestones: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const years=items(cue,props,["years","items"],5); const subtitles=strings(props?.itemSubtitles ?? props?.subLabels); return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:118,top:BODY_TOP,width:1180}}><div style={{color:GOLD,fontSize:18,fontWeight:950,letterSpacing:5}}>{text(cue,props,"label","TIME REWIND")}</div><div style={{position:"relative",height:275,marginTop:24}}><div style={{position:"absolute",top:58,left:"7%",right:"7%",height:4,background:"rgba(255,255,255,.72)"}}/>{years.map((year,i)=>{const x=years.length===1?50:8+(i/(years.length-1))*84;const p=spring({frame:f-s-16-i*14,fps,config:{damping:16,stiffness:150}});return <div key={year+i} style={{position:"absolute",left:x+"%",top:0,width:210,marginLeft:-105,transform:"scale("+interpolate(p,[0,1],[.8,1])+")",transformOrigin:"top center",opacity:Math.min(1,p),textAlign:"center",overflow:"hidden"}}><i style={{display:"block",width:30,height:30,margin:"0 auto 43px",borderRadius:"50%",background:i===years.length-1?GOLD:BLUE,boxShadow:"0 0 18px "+(i===years.length-1?GOLD:BLUE)}}/><b style={{display:"block",fontSize:46,color:WHITE,lineHeight:1.08,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{year}</b><span style={{display:"block",marginTop:15,fontSize:16,color:DIM,fontWeight:900,letterSpacing:2,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{subtitles[i] || text(cue,props,"milestoneLabel","CAPABILITY")}</span></div>})}<b style={{position:"absolute",right:78,top:196,color:GOLD,fontSize:20}}>&lt;&lt; REWIND</b></div></div></div>; };

export const FlyingPaperStack: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const cards: Array<[number, number, string]>=[[-90,-45,GOLD],[0,0,GOLD],[90,45,GOLD]]; const headline=text(cue,props,"headline",cue.section.subtitle); const body=text(cue,props,"body",text(cue,props,"bodyText",text(cue,props,"effectText",cue.caption.zh))); const headlineLength=Array.from(headline).length; const bodyLength=Array.from(body).length; const titleFontSize = headlineLength > 48 ? 38 : headlineLength > 34 ? 46 : headlineLength > 24 ? 52 : 56; const bodyFontSize = bodyLength > 150 ? 20 : bodyLength > 110 ? 23 : bodyLength > 78 ? 26 : 29; return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:190,top:BODY_TOP,width:1050,height:520}}>{cards.map(([x,y,color],i)=>{const p=spring({frame:f-s-10-i*10,fps,config:{damping:15,stiffness:150}});return <div key={i} style={{position:"absolute",inset:0,padding:"58px 70px",background:"#F6F0E2",color:"#101826",borderTop:"14px solid "+color,boxShadow:"0 18px 42px rgba(0,0,0,.36)",opacity:Math.min(1,p),transform:"translate("+interpolate(p,[0,1],[x*2,x])+"px,"+interpolate(p,[0,1],[y*2,y])+"px) rotate("+(i-1)*2+"deg)"}}><div style={{fontSize:20,fontWeight:950,letterSpacing:6}}>THE PRODUCT PAPER</div><div style={{marginTop:36,fontSize:titleFontSize,lineHeight:(titleFontSize * 1.16)+"px",fontWeight:950,overflowWrap:"break-word",wordBreak:"keep-all"}}>{i===2?headline:text(cue,props,"ghostTitle",cue.section.subtitle)}</div><div style={{marginTop:24,borderTop:"2px solid #7E8794"}}/>{i === 2 ? <div data-flying-paper-body style={{marginTop:20,fontSize:bodyFontSize,lineHeight:(bodyFontSize * 1.3)+"px",fontWeight:850,overflowWrap:"break-word",wordBreak:"keep-all"}}>{body}</div> : null}</div>})}</div></div>; };

export const ChecklistEditorial: React.FC<LayoutEffectProps> = ({cue, props}) => { const f=useCurrentFrame(); const {fps}=useVideoConfig(); const s=start(cue,fps)+12; const rows=items(cue,props); const isSingleItem=rows.length===1; return <div style={{position:"absolute",inset:0}}>{header(cue,props)}<div style={{position:"absolute",left:105,top:BODY_TOP,width:860,...enter(f,s)}}><div style={{color:GOLD,fontSize:24,fontWeight:950,letterSpacing:6}}>{text(cue,props,"label",cue.section.eyebrow)}</div><div style={{marginTop:28,color:WHITE,fontSize:72,lineHeight:"86px",fontWeight:950}}>重点简要内容</div><div style={{display:"grid",gap:isSingleItem?0:24,marginTop:isSingleItem?62:38,minHeight:isSingleItem?220:undefined,alignContent:isSingleItem?"center":undefined}}>{rows.map((row,i)=><div key={row+i} style={{display:"flex",alignItems:"center",gap:20,minHeight:isSingleItem?132:undefined,justifyContent:isSingleItem?"center":"flex-start",...enter(f,s+18+i*17,-24,0)}}><span style={{width:54,height:54,flex:"0 0 auto",border:"3px solid "+BLUE,color:BLUE,fontSize:40,lineHeight:"48px",textAlign:"center"}}>✓</span><b style={{minWidth:0,fontSize:isSingleItem?48:42,lineHeight:1.24,color:WHITE,overflowWrap:"break-word",wordBreak:"keep-all"}}>{row}</b></div>)}</div></div></div>; };

